/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Thu Sep 10 13:51:37 2020. */

#ifndef PB_PROTOBUF_MOJINGCMD_PB_H_INCLUDED
#define PB_PROTOBUF_MOJINGCMD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protobuf_DeviceChannelInfoRequest {
    pb_callback_t ChannelCode;
    pb_callback_t DeviceCode;
/* @@protoc_insertion_point(struct:protobuf_DeviceChannelInfoRequest) */
} protobuf_DeviceChannelInfoRequest;

typedef struct _protobuf_GetImageConfigRequest {
    pb_callback_t ChannelCode;
/* @@protoc_insertion_point(struct:protobuf_GetImageConfigRequest) */
} protobuf_GetImageConfigRequest;

typedef struct _protobuf_UploadDeviceInfoRequest {
    pb_callback_t DeviceID;
    pb_callback_t DeviceName;
    pb_callback_t FirmwareVersion;
    pb_callback_t FirmwareMD5;
    pb_callback_t SoftwareVersion;
    pb_callback_t SoftwareMD5;
    pb_callback_t HardwareVersion;
/* @@protoc_insertion_point(struct:protobuf_UploadDeviceInfoRequest) */
} protobuf_UploadDeviceInfoRequest;

typedef struct _protobuf_Area {
    pb_size_t Points_count;
    char Points[6][10];
    pb_callback_t Resolution;
/* @@protoc_insertion_point(struct:protobuf_Area) */
} protobuf_Area;

typedef struct _protobuf_AudioAlarmFile {
    int32_t Index;
    pb_callback_t Name;
    int32_t Status;
    int32_t Type;
/* @@protoc_insertion_point(struct:protobuf_AudioAlarmFile) */
} protobuf_AudioAlarmFile;

typedef struct _protobuf_AudioAlarmFileUpdateNotify {
    int32_t UpdateType;
    pb_callback_t TaskID;
    pb_callback_t Message;
/* @@protoc_insertion_point(struct:protobuf_AudioAlarmFileUpdateNotify) */
} protobuf_AudioAlarmFileUpdateNotify;

typedef struct _protobuf_CloudStorageEndNotify {
    pb_callback_t DeviceID;
    pb_callback_t TaskID;
    int64_t StartTime;
    int64_t EndTime;
/* @@protoc_insertion_point(struct:protobuf_CloudStorageEndNotify) */
} protobuf_CloudStorageEndNotify;

typedef struct _protobuf_CloudStorageInfoChangeNotify {
    pb_callback_t DeviceID;
    int32_t CloudStorageType;
    int32_t StreamType;
    int32_t PreStorageTime;
    int32_t KeepTime;
/* @@protoc_insertion_point(struct:protobuf_CloudStorageInfoChangeNotify) */
} protobuf_CloudStorageInfoChangeNotify;

typedef struct _protobuf_Composition {
    int32_t Index;
    pb_callback_t Name;
    int32_t Display;
/* @@protoc_insertion_point(struct:protobuf_Composition) */
} protobuf_Composition;

typedef struct _protobuf_DeviceUpdateNotify {
    int32_t UpdateType;
    pb_callback_t TaskID;
    pb_callback_t wareVersion;
    pb_callback_t wareMD5;
    int64_t UpdateTime;
/* @@protoc_insertion_point(struct:protobuf_DeviceUpdateNotify) */
} protobuf_DeviceUpdateNotify;

typedef struct _protobuf_DeviceUpdateRequest {
    int32_t UpdateType;
    pb_callback_t wareURL;
    pb_callback_t wareVersion;
    pb_callback_t wareMD5;
    pb_callback_t TaskID;
    int32_t KeepSilence;
/* @@protoc_insertion_point(struct:protobuf_DeviceUpdateRequest) */
} protobuf_DeviceUpdateRequest;

typedef struct _protobuf_DeviceUpdateResponse {
    int32_t Code;
    pb_callback_t Message;
/* @@protoc_insertion_point(struct:protobuf_DeviceUpdateResponse) */
} protobuf_DeviceUpdateResponse;

typedef struct _protobuf_DownLoadStatRequest {
    int32_t DownLoadStat;
    pb_callback_t Message;
/* @@protoc_insertion_point(struct:protobuf_DownLoadStatRequest) */
} protobuf_DownLoadStatRequest;

typedef struct _protobuf_FormatSDCardRequest {
    int64_t Date;
/* @@protoc_insertion_point(struct:protobuf_FormatSDCardRequest) */
} protobuf_FormatSDCardRequest;

typedef struct _protobuf_FromatSDCardStatNotify {
    int32_t FromatSDCardStat;
    pb_callback_t Message;
/* @@protoc_insertion_point(struct:protobuf_FromatSDCardStatNotify) */
} protobuf_FromatSDCardStatNotify;

typedef struct _protobuf_GetAreaAlarmStatusRequest {
    int32_t PresetPosition;
/* @@protoc_insertion_point(struct:protobuf_GetAreaAlarmStatusRequest) */
} protobuf_GetAreaAlarmStatusRequest;

typedef struct _protobuf_GetAudioConfigResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t AudioOutStatus;
    int32_t AudioOut;
    int32_t AudioInStatus;
    int32_t AudioIn;
/* @@protoc_insertion_point(struct:protobuf_GetAudioConfigResponse) */
} protobuf_GetAudioConfigResponse;

typedef struct _protobuf_GetCloudStorageAddrRequest {
    pb_callback_t DeviceID;
    int32_t CloudStorageType;
    int32_t StreamType;
    int32_t PreStorageTime;
    int32_t KeepTime;
    pb_callback_t StreamDesc;
    int64_t StartTime;
/* @@protoc_insertion_point(struct:protobuf_GetCloudStorageAddrRequest) */
} protobuf_GetCloudStorageAddrRequest;

typedef struct _protobuf_GetCloudStorageAddrResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t SSRC;
    pb_callback_t AddrIP;
    int32_t AddrPort;
    int32_t TransType;
    pb_callback_t TaskID;
/* @@protoc_insertion_point(struct:protobuf_GetCloudStorageAddrResponse) */
} protobuf_GetCloudStorageAddrResponse;

typedef struct _protobuf_GetCloudStorageInfoRequest {
    pb_callback_t DeviceID;
    int64_t Time;
/* @@protoc_insertion_point(struct:protobuf_GetCloudStorageInfoRequest) */
} protobuf_GetCloudStorageInfoRequest;

typedef struct _protobuf_GetCloudStorageInfoResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t CloudStorageType;
    int32_t StreamType;
    int32_t PreStorageTime;
    int32_t KeepTime;
/* @@protoc_insertion_point(struct:protobuf_GetCloudStorageInfoResponse) */
} protobuf_GetCloudStorageInfoResponse;

typedef struct _protobuf_GetDeviceOnvifResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t Status;
    pb_callback_t Version;
/* @@protoc_insertion_point(struct:protobuf_GetDeviceOnvifResponse) */
} protobuf_GetDeviceOnvifResponse;

typedef struct _protobuf_GetEventAlarmOutRequest {
    int32_t EventType;
/* @@protoc_insertion_point(struct:protobuf_GetEventAlarmOutRequest) */
} protobuf_GetEventAlarmOutRequest;

typedef struct _protobuf_GetGBConfigResponse {
    int32_t Code;
    pb_callback_t Message;
    pb_callback_t SipHost;
    int32_t SipPort;
    int32_t HeartBeatNum;
    int32_t HearBeatTime;
    pb_callback_t SipServerID;
/* @@protoc_insertion_point(struct:protobuf_GetGBConfigResponse) */
} protobuf_GetGBConfigResponse;

typedef struct _protobuf_GetNightVisionConfigResponse {
    int32_t Code;
    pb_callback_t Message;
    pb_size_t SupportedLightTypes_count;
    int32_t SupportedLightTypes[4];
    int32_t CurrentLightType;
    int32_t LightnessType;
/* @@protoc_insertion_point(struct:protobuf_GetNightVisionConfigResponse) */
} protobuf_GetNightVisionConfigResponse;

typedef struct _protobuf_GetSDCardInfoRequest {
    int64_t Date;
/* @@protoc_insertion_point(struct:protobuf_GetSDCardInfoRequest) */
} protobuf_GetSDCardInfoRequest;

typedef struct _protobuf_GetSDCardInfoResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t SDStat;
    int32_t SDCardSize;
    int32_t SDCardAvailableSize;
    int32_t SDCardUsedSize;
/* @@protoc_insertion_point(struct:protobuf_GetSDCardInfoResponse) */
} protobuf_GetSDCardInfoResponse;

typedef struct _protobuf_GetTimingConfigResponse {
    int32_t Code;
    pb_callback_t Message;
    pb_callback_t NTPHost;
    int32_t TimingInterval;
/* @@protoc_insertion_point(struct:protobuf_GetTimingConfigResponse) */
} protobuf_GetTimingConfigResponse;

typedef struct _protobuf_GetVideoConfigRequest {
    int32_t StreamType;
    pb_callback_t ChannelCode;
/* @@protoc_insertion_point(struct:protobuf_GetVideoConfigRequest) */
} protobuf_GetVideoConfigRequest;

typedef struct _protobuf_GetVideoConfigResponse {
    int32_t Code;
    pb_callback_t Message;
    pb_callback_t CurrResolution;
    pb_size_t Resolution_count;
    char Resolution[5][10];
    pb_callback_t CurrImageQuality;
    pb_size_t ImageQuality_count;
    char ImageQuality[4][6];
    int32_t RateType;
    pb_callback_t RateLimit;
    int32_t Rate;
    int32_t IframeInterval;
    pb_size_t FrameRateLimit_count;
    int32_t FrameRateLimit[4];
    int32_t CurrFrameRate;
    pb_size_t EncodeType_count;
    char EncodeType[3][6];
    pb_callback_t CurrEncode;
/* @@protoc_insertion_point(struct:protobuf_GetVideoConfigResponse) */
} protobuf_GetVideoConfigResponse;

typedef struct _protobuf_ImageParam {
    int32_t Current;
    pb_callback_t Name;
/* @@protoc_insertion_point(struct:protobuf_ImageParam) */
} protobuf_ImageParam;

typedef struct _protobuf_NetCardInfo {
    pb_callback_t IP;
    pb_callback_t Mac;
    int32_t IsDynamic;
    int32_t Status;
    int32_t NetCardType;
/* @@protoc_insertion_point(struct:protobuf_NetCardInfo) */
} protobuf_NetCardInfo;

typedef struct _protobuf_OperateResponse {
    int32_t Code;
    pb_callback_t Message;
/* @@protoc_insertion_point(struct:protobuf_OperateResponse) */
} protobuf_OperateResponse;

typedef struct _protobuf_Ping {
    int64_t Time;
/* @@protoc_insertion_point(struct:protobuf_Ping) */
} protobuf_Ping;

typedef struct _protobuf_Pong {
    int32_t Code;
    pb_callback_t Message;
    int64_t Time;
/* @@protoc_insertion_point(struct:protobuf_Pong) */
} protobuf_Pong;

typedef struct _protobuf_RegisterRequest {
    pb_callback_t DeviceID;
    int64_t RegisterTime;
/* @@protoc_insertion_point(struct:protobuf_RegisterRequest) */
} protobuf_RegisterRequest;

typedef struct _protobuf_RegisterRequestWithAuth {
    pb_callback_t DeviceID;
    int64_t RegisterTime;
    pb_callback_t Auth;
    int32_t PingSpan;
/* @@protoc_insertion_point(struct:protobuf_RegisterRequestWithAuth) */
} protobuf_RegisterRequestWithAuth;

typedef struct _protobuf_RegisterResponse {
    int32_t Code;
    pb_callback_t Message;
    int64_t Time;
/* @@protoc_insertion_point(struct:protobuf_RegisterResponse) */
} protobuf_RegisterResponse;

typedef struct _protobuf_RegisterResponseWithNonce {
    int32_t Code;
    pb_callback_t Message;
    pb_callback_t nonce;
/* @@protoc_insertion_point(struct:protobuf_RegisterResponseWithNonce) */
} protobuf_RegisterResponseWithNonce;

typedef struct _protobuf_SetAudioAlarmFileRequest {
    int32_t Action;
    pb_callback_t FileUrl;
    pb_callback_t FileMD5;
    pb_callback_t FileName;
    int32_t FileIndex;
    pb_callback_t TaskID;
/* @@protoc_insertion_point(struct:protobuf_SetAudioAlarmFileRequest) */
} protobuf_SetAudioAlarmFileRequest;

typedef struct _protobuf_SetAudioConfigRequest {
    int32_t Type;
    int32_t Status;
    int32_t Value;
/* @@protoc_insertion_point(struct:protobuf_SetAudioConfigRequest) */
} protobuf_SetAudioConfigRequest;

typedef struct _protobuf_SetDeviceOnvifRequest {
    int32_t Status;
/* @@protoc_insertion_point(struct:protobuf_SetDeviceOnvifRequest) */
} protobuf_SetDeviceOnvifRequest;

typedef struct _protobuf_SetEventAlarmOutRequest {
    int32_t EventType;
    int32_t GBAlarmStatus;
    int32_t AudioAlarmStatus;
    int32_t AudioAlarmFileIndex;
    int32_t AudioPlayCount;
    int32_t LightAlarmStatus;
    int32_t LightAlarmType;
    int32_t LightAlarmFrequency;
    int32_t LightAlarmTime;
/* @@protoc_insertion_point(struct:protobuf_SetEventAlarmOutRequest) */
} protobuf_SetEventAlarmOutRequest;

typedef struct _protobuf_SetEventUploadRequest {
    int32_t UploadStatus;
    pb_callback_t Host;
    int32_t Port;
/* @@protoc_insertion_point(struct:protobuf_SetEventUploadRequest) */
} protobuf_SetEventUploadRequest;

typedef struct _protobuf_SetLightnessRequest {
    int32_t Lightness;
/* @@protoc_insertion_point(struct:protobuf_SetLightnessRequest) */
} protobuf_SetLightnessRequest;

typedef struct _protobuf_SetManualAlarmRequest {
    int32_t Type;
/* @@protoc_insertion_point(struct:protobuf_SetManualAlarmRequest) */
} protobuf_SetManualAlarmRequest;

typedef struct _protobuf_SetNightLightTypeRequest {
    int32_t LightType;
/* @@protoc_insertion_point(struct:protobuf_SetNightLightTypeRequest) */
} protobuf_SetNightLightTypeRequest;

typedef struct _protobuf_SetTimingConfigRequest {
    pb_callback_t NTPHost;
    int32_t TimingInterval;
    pb_callback_t PassWord;
/* @@protoc_insertion_point(struct:protobuf_SetTimingConfigRequest) */
} protobuf_SetTimingConfigRequest;

typedef struct _protobuf_SetVideoConfigRequest {
    pb_callback_t ChannelCode;
    pb_callback_t CurrResolution;
    pb_callback_t CurrImageQuality;
    int32_t RateType;
    int32_t Rate;
    int32_t IframeInterval;
    int32_t CurrFrameRate;
    pb_callback_t CurrEncode;
    int32_t StreamType;
/* @@protoc_insertion_point(struct:protobuf_SetVideoConfigRequest) */
} protobuf_SetVideoConfigRequest;

typedef struct _protobuf_TimeDurationList {
    pb_size_t TimeDuration_count;
    char TimeDuration[24][16];
    int32_t WeekDay;
/* @@protoc_insertion_point(struct:protobuf_TimeDurationList) */
} protobuf_TimeDurationList;

typedef struct _protobuf_UpdateGBConfigRequest {
    pb_callback_t SipHost;
    int32_t SipPort;
    int32_t HeartBeatNum;
    int32_t HearBeatTime;
    pb_callback_t SipServerID;
    pb_callback_t GBPassword;
/* @@protoc_insertion_point(struct:protobuf_UpdateGBConfigRequest) */
} protobuf_UpdateGBConfigRequest;

typedef struct _protobuf_UpdateNetInfoRequest {
    pb_callback_t Mac;
    int32_t Conversion;
/* @@protoc_insertion_point(struct:protobuf_UpdateNetInfoRequest) */
} protobuf_UpdateNetInfoRequest;

typedef struct _protobuf_UploadDeviceInfoResponse {
    int32_t Code;
    pb_callback_t Message;
/* @@protoc_insertion_point(struct:protobuf_UploadDeviceInfoResponse) */
} protobuf_UploadDeviceInfoResponse;

typedef struct _protobuf_GetAreaAlarmStatusResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t EventStatus;
    int32_t Sensitivity;
    int32_t SmartStatus;
    pb_size_t SmartType_count;
    int32_t SmartType[4];
    pb_size_t Action_count;
    int32_t Action[5];
    pb_size_t AreaGroup_count;
    protobuf_Area AreaGroup[3];
    int32_t ScreenShotStatus;
    int32_t DefenceStatus;
    pb_size_t DefenceTime_count;
    protobuf_TimeDurationList DefenceTime[7];
    int32_t ShowArea;
/* @@protoc_insertion_point(struct:protobuf_GetAreaAlarmStatusResponse) */
} protobuf_GetAreaAlarmStatusResponse;

typedef struct _protobuf_GetEventAlarmOutResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t GBAlarmStatus;
    int32_t AudioAlarmStatus;
    pb_size_t AudioAlarmFiles_count;
    protobuf_AudioAlarmFile AudioAlarmFiles[8];
    int32_t AudioPlayCount;
    int32_t LightAlarmStatus;
    int32_t LightAlarmType;
    int32_t LightAlarmFrequency;
    int32_t LightAlarmTime;
/* @@protoc_insertion_point(struct:protobuf_GetEventAlarmOutResponse) */
} protobuf_GetEventAlarmOutResponse;

typedef struct _protobuf_GetLocalStorageConfigResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t StreamType;
    int32_t StorageType;
    pb_size_t DefenceTime_count;
    protobuf_TimeDurationList DefenceTime[7];
/* @@protoc_insertion_point(struct:protobuf_GetLocalStorageConfigResponse) */
} protobuf_GetLocalStorageConfigResponse;

typedef struct _protobuf_GetMDStatusResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t EventStatus;
    int32_t Sensitivity;
    int32_t ScreenShotStatus;
    int32_t SmartStatus;
    pb_size_t SmartType_count;
    int32_t SmartType[4];
    int32_t DefenceStatus;
    pb_size_t DefenceTime_count;
    protobuf_TimeDurationList DefenceTime[7];
/* @@protoc_insertion_point(struct:protobuf_GetMDStatusResponse) */
} protobuf_GetMDStatusResponse;

typedef struct _protobuf_ImageType {
    pb_callback_t Type;
    pb_size_t Params_count;
    protobuf_ImageParam Params[5];
/* @@protoc_insertion_point(struct:protobuf_ImageType) */
} protobuf_ImageType;

typedef struct _protobuf_NetInfoResponse {
    int32_t Code;
    pb_callback_t Message;
    pb_size_t NetCards_count;
    protobuf_NetCardInfo NetCards[2];
/* @@protoc_insertion_point(struct:protobuf_NetInfoResponse) */
} protobuf_NetInfoResponse;

typedef struct _protobuf_OSDConfigResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t WeekDisplay;
    int32_t DateDisplay;
    int32_t ChannelDisplay;
    pb_callback_t Channel;
    pb_size_t Compositions_count;
    protobuf_Composition Compositions[6];
/* @@protoc_insertion_point(struct:protobuf_OSDConfigResponse) */
} protobuf_OSDConfigResponse;

typedef struct _protobuf_SetAreaAlarmStatusRequest {
    int32_t EventStatus;
    int32_t Sensitivity;
    int32_t SmartStatus;
    pb_size_t SmartType_count;
    int32_t SmartType[4];
    pb_size_t Action_count;
    int32_t Action[5];
    pb_size_t AreaGroup_count;
    protobuf_Area AreaGroup[3];
    int32_t ScreenShotStatus;
    int32_t DefenceStatus;
    pb_size_t DefenceTime_count;
    protobuf_TimeDurationList DefenceTime[7];
    int32_t ShowArea;
    int32_t PresetPosition;
/* @@protoc_insertion_point(struct:protobuf_SetAreaAlarmStatusRequest) */
} protobuf_SetAreaAlarmStatusRequest;

typedef struct _protobuf_SetLocalStorageConfigRequest {
    int32_t StreamType;
    int32_t StorageType;
    pb_size_t DefenceTime_count;
    protobuf_TimeDurationList DefenceTime[7];
/* @@protoc_insertion_point(struct:protobuf_SetLocalStorageConfigRequest) */
} protobuf_SetLocalStorageConfigRequest;

typedef struct _protobuf_SetMDStatusRequest {
    int32_t EventStatus;
    int32_t Sensitivity;
    int32_t ScreenShotStatus;
    int32_t SmartStatus;
    pb_size_t SmartType_count;
    int32_t SmartType[4];
    int32_t DefenceStatus;
    pb_size_t DefenceTime_count;
    protobuf_TimeDurationList DefenceTime[7];
/* @@protoc_insertion_point(struct:protobuf_SetMDStatusRequest) */
} protobuf_SetMDStatusRequest;

typedef struct _protobuf_SetOSDConfigRequest {
    pb_callback_t ChannelCode;
    int32_t WeekDisplay;
    int32_t DateDisplay;
    int32_t ChannelDisplay;
    pb_callback_t Channel;
    pb_size_t Compositions_count;
    protobuf_Composition Compositions[6];
/* @@protoc_insertion_point(struct:protobuf_SetOSDConfigRequest) */
} protobuf_SetOSDConfigRequest;

typedef struct _protobuf_GetImageConfigResponse {
    int32_t Code;
    pb_callback_t Message;
    int32_t Model;
    pb_size_t Types_count;
    protobuf_ImageType Types[3];
/* @@protoc_insertion_point(struct:protobuf_GetImageConfigResponse) */
} protobuf_GetImageConfigResponse;

typedef struct _protobuf_SetImageConfigRequest {
    pb_callback_t ChannelCode;
    int32_t Model;
    pb_size_t Types_count;
    protobuf_ImageType Types[3];
/* @@protoc_insertion_point(struct:protobuf_SetImageConfigRequest) */
} protobuf_SetImageConfigRequest;

/* Default values for struct fields */

/* Initializer values for message structs */
#define protobuf_RegisterRequest_init_default    {{{NULL}, NULL}, 0}
#define protobuf_RegisterResponseWithNonce_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_RegisterRequestWithAuth_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define protobuf_RegisterResponse_init_default   {0, {{NULL}, NULL}, 0}
#define protobuf_UploadDeviceInfoRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_UploadDeviceInfoResponse_init_default {0, {{NULL}, NULL}}
#define protobuf_Ping_init_default               {0}
#define protobuf_Pong_init_default               {0, {{NULL}, NULL}, 0}
#define protobuf_DeviceUpdateRequest_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protobuf_DeviceUpdateResponse_init_default {0, {{NULL}, NULL}}
#define protobuf_DeviceUpdateNotify_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protobuf_OperateResponse_init_default    {0, {{NULL}, NULL}}
#define protobuf_GetSDCardInfoRequest_init_default {0}
#define protobuf_GetSDCardInfoResponse_init_default {0, {{NULL}, NULL}, 0, 0, 0, 0}
#define protobuf_FormatSDCardRequest_init_default {0}
#define protobuf_DownLoadStatRequest_init_default {0, {{NULL}, NULL}}
#define protobuf_FromatSDCardStatNotify_init_default {0, {{NULL}, NULL}}
#define protobuf_GetCloudStorageInfoRequest_init_default {{{NULL}, NULL}, 0}
#define protobuf_GetCloudStorageInfoResponse_init_default {0, {{NULL}, NULL}, 0, 0, 0, 0}
#define protobuf_CloudStorageInfoChangeNotify_init_default {{{NULL}, NULL}, 0, 0, 0, 0}
#define protobuf_GetCloudStorageAddrRequest_init_default {{{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, 0}
#define protobuf_GetCloudStorageAddrResponse_init_default {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define protobuf_CloudStorageEndNotify_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define protobuf_GetVideoConfigRequest_init_default {0, {{NULL}, NULL}}
#define protobuf_GetVideoConfigResponse_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, {"", "", "", "", ""}, {{NULL}, NULL}, 0, {"", "", "", ""}, 0, {{NULL}, NULL}, 0, 0, 0, {0, 0, 0, 0}, 0, 0, {"", "", ""}, {{NULL}, NULL}}
#define protobuf_SetVideoConfigRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, 0}
#define protobuf_GetImageConfigRequest_init_default {{{NULL}, NULL}}
#define protobuf_GetImageConfigResponse_init_default {0, {{NULL}, NULL}, 0, 0, {protobuf_ImageType_init_default, protobuf_ImageType_init_default, protobuf_ImageType_init_default}}
#define protobuf_ImageType_init_default          {{{NULL}, NULL}, 0, {protobuf_ImageParam_init_default, protobuf_ImageParam_init_default, protobuf_ImageParam_init_default, protobuf_ImageParam_init_default, protobuf_ImageParam_init_default}}
#define protobuf_ImageParam_init_default         {0, {{NULL}, NULL}}
#define protobuf_SetImageConfigRequest_init_default {{{NULL}, NULL}, 0, 0, {protobuf_ImageType_init_default, protobuf_ImageType_init_default, protobuf_ImageType_init_default}}
#define protobuf_DeviceChannelInfoRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_OSDConfigResponse_init_default  {0, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0, {protobuf_Composition_init_default, protobuf_Composition_init_default, protobuf_Composition_init_default, protobuf_Composition_init_default, protobuf_Composition_init_default, protobuf_Composition_init_default}}
#define protobuf_Composition_init_default        {0, {{NULL}, NULL}, 0}
#define protobuf_SetOSDConfigRequest_init_default {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0, {protobuf_Composition_init_default, protobuf_Composition_init_default, protobuf_Composition_init_default, protobuf_Composition_init_default, protobuf_Composition_init_default, protobuf_Composition_init_default}}
#define protobuf_GetMDStatusResponse_init_default {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, {0, 0, 0, 0}, 0, 0, {protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default}}
#define protobuf_TimeDurationList_init_default   {0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, 0}
#define protobuf_SetMDStatusRequest_init_default {0, 0, 0, 0, 0, {0, 0, 0, 0}, 0, 0, {protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default}}
#define protobuf_GetAreaAlarmStatusRequest_init_default {0}
#define protobuf_GetAreaAlarmStatusResponse_init_default {0, {{NULL}, NULL}, 0, 0, 0, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0, 0}, 0, {protobuf_Area_init_default, protobuf_Area_init_default, protobuf_Area_init_default}, 0, 0, 0, {protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default}, 0}
#define protobuf_Area_init_default               {0, {"", "", "", "", "", ""}, {{NULL}, NULL}}
#define protobuf_SetAreaAlarmStatusRequest_init_default {0, 0, 0, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0, 0}, 0, {protobuf_Area_init_default, protobuf_Area_init_default, protobuf_Area_init_default}, 0, 0, 0, {protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default}, 0, 0}
#define protobuf_GetEventAlarmOutRequest_init_default {0}
#define protobuf_GetEventAlarmOutResponse_init_default {0, {{NULL}, NULL}, 0, 0, 0, {protobuf_AudioAlarmFile_init_default, protobuf_AudioAlarmFile_init_default, protobuf_AudioAlarmFile_init_default, protobuf_AudioAlarmFile_init_default, protobuf_AudioAlarmFile_init_default, protobuf_AudioAlarmFile_init_default, protobuf_AudioAlarmFile_init_default, protobuf_AudioAlarmFile_init_default}, 0, 0, 0, 0, 0}
#define protobuf_AudioAlarmFile_init_default     {0, {{NULL}, NULL}, 0, 0}
#define protobuf_SetEventAlarmOutRequest_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_SetManualAlarmRequest_init_default {0}
#define protobuf_SetAudioAlarmFileRequest_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define protobuf_AudioAlarmFileUpdateNotify_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_GetNightVisionConfigResponse_init_default {0, {{NULL}, NULL}, 0, {0, 0, 0, 0}, 0, 0}
#define protobuf_SetNightLightTypeRequest_init_default {0}
#define protobuf_SetLightnessRequest_init_default {0}
#define protobuf_GetAudioConfigResponse_init_default {0, {{NULL}, NULL}, 0, 0, 0, 0}
#define protobuf_SetAudioConfigRequest_init_default {0, 0, 0}
#define protobuf_GetLocalStorageConfigResponse_init_default {0, {{NULL}, NULL}, 0, 0, 0, {protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default}}
#define protobuf_SetLocalStorageConfigRequest_init_default {0, 0, 0, {protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default, protobuf_TimeDurationList_init_default}}
#define protobuf_SetEventUploadRequest_init_default {0, {{NULL}, NULL}, 0}
#define protobuf_GetGBConfigResponse_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define protobuf_UpdateGBConfigRequest_init_default {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_GetTimingConfigResponse_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protobuf_SetTimingConfigRequest_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define protobuf_NetInfoResponse_init_default    {0, {{NULL}, NULL}, 0, {protobuf_NetCardInfo_init_default, protobuf_NetCardInfo_init_default}}
#define protobuf_NetCardInfo_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define protobuf_UpdateNetInfoRequest_init_default {{{NULL}, NULL}, 0}
#define protobuf_GetDeviceOnvifResponse_init_default {0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define protobuf_SetDeviceOnvifRequest_init_default {0}
#define protobuf_RegisterRequest_init_zero       {{{NULL}, NULL}, 0}
#define protobuf_RegisterResponseWithNonce_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_RegisterRequestWithAuth_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define protobuf_RegisterResponse_init_zero      {0, {{NULL}, NULL}, 0}
#define protobuf_UploadDeviceInfoRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_UploadDeviceInfoResponse_init_zero {0, {{NULL}, NULL}}
#define protobuf_Ping_init_zero                  {0}
#define protobuf_Pong_init_zero                  {0, {{NULL}, NULL}, 0}
#define protobuf_DeviceUpdateRequest_init_zero   {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protobuf_DeviceUpdateResponse_init_zero  {0, {{NULL}, NULL}}
#define protobuf_DeviceUpdateNotify_init_zero    {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protobuf_OperateResponse_init_zero       {0, {{NULL}, NULL}}
#define protobuf_GetSDCardInfoRequest_init_zero  {0}
#define protobuf_GetSDCardInfoResponse_init_zero {0, {{NULL}, NULL}, 0, 0, 0, 0}
#define protobuf_FormatSDCardRequest_init_zero   {0}
#define protobuf_DownLoadStatRequest_init_zero   {0, {{NULL}, NULL}}
#define protobuf_FromatSDCardStatNotify_init_zero {0, {{NULL}, NULL}}
#define protobuf_GetCloudStorageInfoRequest_init_zero {{{NULL}, NULL}, 0}
#define protobuf_GetCloudStorageInfoResponse_init_zero {0, {{NULL}, NULL}, 0, 0, 0, 0}
#define protobuf_CloudStorageInfoChangeNotify_init_zero {{{NULL}, NULL}, 0, 0, 0, 0}
#define protobuf_GetCloudStorageAddrRequest_init_zero {{{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, 0}
#define protobuf_GetCloudStorageAddrResponse_init_zero {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define protobuf_CloudStorageEndNotify_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define protobuf_GetVideoConfigRequest_init_zero {0, {{NULL}, NULL}}
#define protobuf_GetVideoConfigResponse_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, {"", "", "", "", ""}, {{NULL}, NULL}, 0, {"", "", "", ""}, 0, {{NULL}, NULL}, 0, 0, 0, {0, 0, 0, 0}, 0, 0, {"", "", ""}, {{NULL}, NULL}}
#define protobuf_SetVideoConfigRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, 0}
#define protobuf_GetImageConfigRequest_init_zero {{{NULL}, NULL}}
#define protobuf_GetImageConfigResponse_init_zero {0, {{NULL}, NULL}, 0, 0, {protobuf_ImageType_init_zero, protobuf_ImageType_init_zero, protobuf_ImageType_init_zero}}
#define protobuf_ImageType_init_zero             {{{NULL}, NULL}, 0, {protobuf_ImageParam_init_zero, protobuf_ImageParam_init_zero, protobuf_ImageParam_init_zero, protobuf_ImageParam_init_zero, protobuf_ImageParam_init_zero}}
#define protobuf_ImageParam_init_zero            {0, {{NULL}, NULL}}
#define protobuf_SetImageConfigRequest_init_zero {{{NULL}, NULL}, 0, 0, {protobuf_ImageType_init_zero, protobuf_ImageType_init_zero, protobuf_ImageType_init_zero}}
#define protobuf_DeviceChannelInfoRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_OSDConfigResponse_init_zero     {0, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0, {protobuf_Composition_init_zero, protobuf_Composition_init_zero, protobuf_Composition_init_zero, protobuf_Composition_init_zero, protobuf_Composition_init_zero, protobuf_Composition_init_zero}}
#define protobuf_Composition_init_zero           {0, {{NULL}, NULL}, 0}
#define protobuf_SetOSDConfigRequest_init_zero   {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0, {protobuf_Composition_init_zero, protobuf_Composition_init_zero, protobuf_Composition_init_zero, protobuf_Composition_init_zero, protobuf_Composition_init_zero, protobuf_Composition_init_zero}}
#define protobuf_GetMDStatusResponse_init_zero   {0, {{NULL}, NULL}, 0, 0, 0, 0, 0, {0, 0, 0, 0}, 0, 0, {protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero}}
#define protobuf_TimeDurationList_init_zero      {0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}, 0}
#define protobuf_SetMDStatusRequest_init_zero    {0, 0, 0, 0, 0, {0, 0, 0, 0}, 0, 0, {protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero}}
#define protobuf_GetAreaAlarmStatusRequest_init_zero {0}
#define protobuf_GetAreaAlarmStatusResponse_init_zero {0, {{NULL}, NULL}, 0, 0, 0, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0, 0}, 0, {protobuf_Area_init_zero, protobuf_Area_init_zero, protobuf_Area_init_zero}, 0, 0, 0, {protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero}, 0}
#define protobuf_Area_init_zero                  {0, {"", "", "", "", "", ""}, {{NULL}, NULL}}
#define protobuf_SetAreaAlarmStatusRequest_init_zero {0, 0, 0, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0, 0}, 0, {protobuf_Area_init_zero, protobuf_Area_init_zero, protobuf_Area_init_zero}, 0, 0, 0, {protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero}, 0, 0}
#define protobuf_GetEventAlarmOutRequest_init_zero {0}
#define protobuf_GetEventAlarmOutResponse_init_zero {0, {{NULL}, NULL}, 0, 0, 0, {protobuf_AudioAlarmFile_init_zero, protobuf_AudioAlarmFile_init_zero, protobuf_AudioAlarmFile_init_zero, protobuf_AudioAlarmFile_init_zero, protobuf_AudioAlarmFile_init_zero, protobuf_AudioAlarmFile_init_zero, protobuf_AudioAlarmFile_init_zero, protobuf_AudioAlarmFile_init_zero}, 0, 0, 0, 0, 0}
#define protobuf_AudioAlarmFile_init_zero        {0, {{NULL}, NULL}, 0, 0}
#define protobuf_SetEventAlarmOutRequest_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_SetManualAlarmRequest_init_zero {0}
#define protobuf_SetAudioAlarmFileRequest_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define protobuf_AudioAlarmFileUpdateNotify_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_GetNightVisionConfigResponse_init_zero {0, {{NULL}, NULL}, 0, {0, 0, 0, 0}, 0, 0}
#define protobuf_SetNightLightTypeRequest_init_zero {0}
#define protobuf_SetLightnessRequest_init_zero   {0}
#define protobuf_GetAudioConfigResponse_init_zero {0, {{NULL}, NULL}, 0, 0, 0, 0}
#define protobuf_SetAudioConfigRequest_init_zero {0, 0, 0}
#define protobuf_GetLocalStorageConfigResponse_init_zero {0, {{NULL}, NULL}, 0, 0, 0, {protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero}}
#define protobuf_SetLocalStorageConfigRequest_init_zero {0, 0, 0, {protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero, protobuf_TimeDurationList_init_zero}}
#define protobuf_SetEventUploadRequest_init_zero {0, {{NULL}, NULL}, 0}
#define protobuf_GetGBConfigResponse_init_zero   {0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define protobuf_UpdateGBConfigRequest_init_zero {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define protobuf_GetTimingConfigResponse_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protobuf_SetTimingConfigRequest_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define protobuf_NetInfoResponse_init_zero       {0, {{NULL}, NULL}, 0, {protobuf_NetCardInfo_init_zero, protobuf_NetCardInfo_init_zero}}
#define protobuf_NetCardInfo_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define protobuf_UpdateNetInfoRequest_init_zero  {{{NULL}, NULL}, 0}
#define protobuf_GetDeviceOnvifResponse_init_zero {0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define protobuf_SetDeviceOnvifRequest_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define protobuf_DeviceChannelInfoRequest_ChannelCode_tag 1
#define protobuf_DeviceChannelInfoRequest_DeviceCode_tag 2
#define protobuf_GetImageConfigRequest_ChannelCode_tag 1
#define protobuf_UploadDeviceInfoRequest_DeviceID_tag 1
#define protobuf_UploadDeviceInfoRequest_DeviceName_tag 2
#define protobuf_UploadDeviceInfoRequest_FirmwareVersion_tag 3
#define protobuf_UploadDeviceInfoRequest_FirmwareMD5_tag 4
#define protobuf_UploadDeviceInfoRequest_SoftwareVersion_tag 5
#define protobuf_UploadDeviceInfoRequest_SoftwareMD5_tag 6
#define protobuf_UploadDeviceInfoRequest_HardwareVersion_tag 7
#define protobuf_Area_Points_tag                 1
#define protobuf_Area_Resolution_tag             2
#define protobuf_AudioAlarmFile_Index_tag        1
#define protobuf_AudioAlarmFile_Name_tag         2
#define protobuf_AudioAlarmFile_Status_tag       3
#define protobuf_AudioAlarmFile_Type_tag         4
#define protobuf_AudioAlarmFileUpdateNotify_UpdateType_tag 1
#define protobuf_AudioAlarmFileUpdateNotify_TaskID_tag 2
#define protobuf_AudioAlarmFileUpdateNotify_Message_tag 3
#define protobuf_CloudStorageEndNotify_DeviceID_tag 1
#define protobuf_CloudStorageEndNotify_TaskID_tag 2
#define protobuf_CloudStorageEndNotify_StartTime_tag 3
#define protobuf_CloudStorageEndNotify_EndTime_tag 4
#define protobuf_CloudStorageInfoChangeNotify_DeviceID_tag 1
#define protobuf_CloudStorageInfoChangeNotify_CloudStorageType_tag 2
#define protobuf_CloudStorageInfoChangeNotify_StreamType_tag 3
#define protobuf_CloudStorageInfoChangeNotify_PreStorageTime_tag 4
#define protobuf_CloudStorageInfoChangeNotify_KeepTime_tag 5
#define protobuf_Composition_Index_tag           1
#define protobuf_Composition_Name_tag            2
#define protobuf_Composition_Display_tag         3
#define protobuf_DeviceUpdateNotify_UpdateType_tag 1
#define protobuf_DeviceUpdateNotify_TaskID_tag   2
#define protobuf_DeviceUpdateNotify_wareVersion_tag 3
#define protobuf_DeviceUpdateNotify_wareMD5_tag  4
#define protobuf_DeviceUpdateNotify_UpdateTime_tag 5
#define protobuf_DeviceUpdateRequest_UpdateType_tag 1
#define protobuf_DeviceUpdateRequest_wareURL_tag 2
#define protobuf_DeviceUpdateRequest_wareVersion_tag 3
#define protobuf_DeviceUpdateRequest_wareMD5_tag 4
#define protobuf_DeviceUpdateRequest_TaskID_tag  5
#define protobuf_DeviceUpdateRequest_KeepSilence_tag 6
#define protobuf_DeviceUpdateResponse_Code_tag   1
#define protobuf_DeviceUpdateResponse_Message_tag 2
#define protobuf_DownLoadStatRequest_DownLoadStat_tag 1
#define protobuf_DownLoadStatRequest_Message_tag 2
#define protobuf_FormatSDCardRequest_Date_tag    1
#define protobuf_FromatSDCardStatNotify_FromatSDCardStat_tag 1
#define protobuf_FromatSDCardStatNotify_Message_tag 2
#define protobuf_GetAreaAlarmStatusRequest_PresetPosition_tag 1
#define protobuf_GetAudioConfigResponse_Code_tag 1
#define protobuf_GetAudioConfigResponse_Message_tag 2
#define protobuf_GetAudioConfigResponse_AudioOutStatus_tag 3
#define protobuf_GetAudioConfigResponse_AudioOut_tag 4
#define protobuf_GetAudioConfigResponse_AudioInStatus_tag 5
#define protobuf_GetAudioConfigResponse_AudioIn_tag 6
#define protobuf_GetCloudStorageAddrRequest_DeviceID_tag 1
#define protobuf_GetCloudStorageAddrRequest_CloudStorageType_tag 2
#define protobuf_GetCloudStorageAddrRequest_StreamType_tag 3
#define protobuf_GetCloudStorageAddrRequest_PreStorageTime_tag 4
#define protobuf_GetCloudStorageAddrRequest_KeepTime_tag 5
#define protobuf_GetCloudStorageAddrRequest_StreamDesc_tag 6
#define protobuf_GetCloudStorageAddrRequest_StartTime_tag 7
#define protobuf_GetCloudStorageAddrResponse_Code_tag 1
#define protobuf_GetCloudStorageAddrResponse_Message_tag 2
#define protobuf_GetCloudStorageAddrResponse_SSRC_tag 3
#define protobuf_GetCloudStorageAddrResponse_AddrIP_tag 4
#define protobuf_GetCloudStorageAddrResponse_AddrPort_tag 5
#define protobuf_GetCloudStorageAddrResponse_TransType_tag 6
#define protobuf_GetCloudStorageAddrResponse_TaskID_tag 7
#define protobuf_GetCloudStorageInfoRequest_DeviceID_tag 1
#define protobuf_GetCloudStorageInfoRequest_Time_tag 2
#define protobuf_GetCloudStorageInfoResponse_Code_tag 1
#define protobuf_GetCloudStorageInfoResponse_Message_tag 2
#define protobuf_GetCloudStorageInfoResponse_CloudStorageType_tag 3
#define protobuf_GetCloudStorageInfoResponse_StreamType_tag 4
#define protobuf_GetCloudStorageInfoResponse_PreStorageTime_tag 5
#define protobuf_GetCloudStorageInfoResponse_KeepTime_tag 6
#define protobuf_GetDeviceOnvifResponse_Code_tag 1
#define protobuf_GetDeviceOnvifResponse_Message_tag 2
#define protobuf_GetDeviceOnvifResponse_Status_tag 3
#define protobuf_GetDeviceOnvifResponse_Version_tag 4
#define protobuf_GetEventAlarmOutRequest_EventType_tag 1
#define protobuf_GetGBConfigResponse_Code_tag    1
#define protobuf_GetGBConfigResponse_Message_tag 2
#define protobuf_GetGBConfigResponse_SipHost_tag 3
#define protobuf_GetGBConfigResponse_SipPort_tag 4
#define protobuf_GetGBConfigResponse_HeartBeatNum_tag 5
#define protobuf_GetGBConfigResponse_HearBeatTime_tag 6
#define protobuf_GetGBConfigResponse_SipServerID_tag 7
#define protobuf_GetNightVisionConfigResponse_Code_tag 1
#define protobuf_GetNightVisionConfigResponse_Message_tag 2
#define protobuf_GetNightVisionConfigResponse_SupportedLightTypes_tag 3
#define protobuf_GetNightVisionConfigResponse_CurrentLightType_tag 4
#define protobuf_GetNightVisionConfigResponse_LightnessType_tag 5
#define protobuf_GetSDCardInfoRequest_Date_tag   1
#define protobuf_GetSDCardInfoResponse_Code_tag  1
#define protobuf_GetSDCardInfoResponse_Message_tag 2
#define protobuf_GetSDCardInfoResponse_SDStat_tag 3
#define protobuf_GetSDCardInfoResponse_SDCardSize_tag 4
#define protobuf_GetSDCardInfoResponse_SDCardAvailableSize_tag 5
#define protobuf_GetSDCardInfoResponse_SDCardUsedSize_tag 6
#define protobuf_GetTimingConfigResponse_Code_tag 1
#define protobuf_GetTimingConfigResponse_Message_tag 2
#define protobuf_GetTimingConfigResponse_NTPHost_tag 3
#define protobuf_GetTimingConfigResponse_TimingInterval_tag 4
#define protobuf_GetVideoConfigRequest_StreamType_tag 1
#define protobuf_GetVideoConfigRequest_ChannelCode_tag 2
#define protobuf_GetVideoConfigResponse_Code_tag 1
#define protobuf_GetVideoConfigResponse_Message_tag 2
#define protobuf_GetVideoConfigResponse_CurrResolution_tag 3
#define protobuf_GetVideoConfigResponse_Resolution_tag 4
#define protobuf_GetVideoConfigResponse_CurrImageQuality_tag 5
#define protobuf_GetVideoConfigResponse_ImageQuality_tag 6
#define protobuf_GetVideoConfigResponse_RateType_tag 7
#define protobuf_GetVideoConfigResponse_RateLimit_tag 8
#define protobuf_GetVideoConfigResponse_Rate_tag 9
#define protobuf_GetVideoConfigResponse_IframeInterval_tag 10
#define protobuf_GetVideoConfigResponse_FrameRateLimit_tag 11
#define protobuf_GetVideoConfigResponse_CurrFrameRate_tag 12
#define protobuf_GetVideoConfigResponse_EncodeType_tag 13
#define protobuf_GetVideoConfigResponse_CurrEncode_tag 14
#define protobuf_ImageParam_Current_tag          1
#define protobuf_ImageParam_Name_tag             2
#define protobuf_NetCardInfo_IP_tag              1
#define protobuf_NetCardInfo_Mac_tag             2
#define protobuf_NetCardInfo_IsDynamic_tag       3
#define protobuf_NetCardInfo_Status_tag          4
#define protobuf_NetCardInfo_NetCardType_tag     5
#define protobuf_OperateResponse_Code_tag        1
#define protobuf_OperateResponse_Message_tag     2
#define protobuf_Ping_Time_tag                   1
#define protobuf_Pong_Code_tag                   1
#define protobuf_Pong_Message_tag                2
#define protobuf_Pong_Time_tag                   3
#define protobuf_RegisterRequest_DeviceID_tag    1
#define protobuf_RegisterRequest_RegisterTime_tag 2
#define protobuf_RegisterRequestWithAuth_DeviceID_tag 1
#define protobuf_RegisterRequestWithAuth_RegisterTime_tag 2
#define protobuf_RegisterRequestWithAuth_Auth_tag 3
#define protobuf_RegisterRequestWithAuth_PingSpan_tag 4
#define protobuf_RegisterResponse_Code_tag       1
#define protobuf_RegisterResponse_Message_tag    2
#define protobuf_RegisterResponse_Time_tag       3
#define protobuf_RegisterResponseWithNonce_Code_tag 1
#define protobuf_RegisterResponseWithNonce_Message_tag 2
#define protobuf_RegisterResponseWithNonce_nonce_tag 3
#define protobuf_SetAudioAlarmFileRequest_Action_tag 1
#define protobuf_SetAudioAlarmFileRequest_FileUrl_tag 2
#define protobuf_SetAudioAlarmFileRequest_FileMD5_tag 3
#define protobuf_SetAudioAlarmFileRequest_FileName_tag 4
#define protobuf_SetAudioAlarmFileRequest_FileIndex_tag 5
#define protobuf_SetAudioAlarmFileRequest_TaskID_tag 6
#define protobuf_SetAudioConfigRequest_Type_tag  1
#define protobuf_SetAudioConfigRequest_Status_tag 2
#define protobuf_SetAudioConfigRequest_Value_tag 3
#define protobuf_SetDeviceOnvifRequest_Status_tag 1
#define protobuf_SetEventAlarmOutRequest_EventType_tag 1
#define protobuf_SetEventAlarmOutRequest_GBAlarmStatus_tag 2
#define protobuf_SetEventAlarmOutRequest_AudioAlarmStatus_tag 3
#define protobuf_SetEventAlarmOutRequest_AudioAlarmFileIndex_tag 4
#define protobuf_SetEventAlarmOutRequest_AudioPlayCount_tag 5
#define protobuf_SetEventAlarmOutRequest_LightAlarmStatus_tag 6
#define protobuf_SetEventAlarmOutRequest_LightAlarmType_tag 7
#define protobuf_SetEventAlarmOutRequest_LightAlarmFrequency_tag 8
#define protobuf_SetEventAlarmOutRequest_LightAlarmTime_tag 9
#define protobuf_SetEventUploadRequest_UploadStatus_tag 1
#define protobuf_SetEventUploadRequest_Host_tag  2
#define protobuf_SetEventUploadRequest_Port_tag  3
#define protobuf_SetLightnessRequest_Lightness_tag 1
#define protobuf_SetManualAlarmRequest_Type_tag  1
#define protobuf_SetNightLightTypeRequest_LightType_tag 1
#define protobuf_SetTimingConfigRequest_NTPHost_tag 1
#define protobuf_SetTimingConfigRequest_TimingInterval_tag 2
#define protobuf_SetTimingConfigRequest_PassWord_tag 3
#define protobuf_SetVideoConfigRequest_ChannelCode_tag 1
#define protobuf_SetVideoConfigRequest_CurrResolution_tag 2
#define protobuf_SetVideoConfigRequest_CurrImageQuality_tag 3
#define protobuf_SetVideoConfigRequest_RateType_tag 4
#define protobuf_SetVideoConfigRequest_Rate_tag  5
#define protobuf_SetVideoConfigRequest_IframeInterval_tag 6
#define protobuf_SetVideoConfigRequest_CurrFrameRate_tag 7
#define protobuf_SetVideoConfigRequest_CurrEncode_tag 8
#define protobuf_SetVideoConfigRequest_StreamType_tag 9
#define protobuf_TimeDurationList_TimeDuration_tag 1
#define protobuf_TimeDurationList_WeekDay_tag    2
#define protobuf_UpdateGBConfigRequest_SipHost_tag 1
#define protobuf_UpdateGBConfigRequest_SipPort_tag 2
#define protobuf_UpdateGBConfigRequest_HeartBeatNum_tag 3
#define protobuf_UpdateGBConfigRequest_HearBeatTime_tag 4
#define protobuf_UpdateGBConfigRequest_SipServerID_tag 5
#define protobuf_UpdateGBConfigRequest_GBPassword_tag 6
#define protobuf_UpdateNetInfoRequest_Mac_tag    1
#define protobuf_UpdateNetInfoRequest_Conversion_tag 2
#define protobuf_UploadDeviceInfoResponse_Code_tag 1
#define protobuf_UploadDeviceInfoResponse_Message_tag 2
#define protobuf_GetAreaAlarmStatusResponse_Code_tag 1
#define protobuf_GetAreaAlarmStatusResponse_Message_tag 2
#define protobuf_GetAreaAlarmStatusResponse_EventStatus_tag 3
#define protobuf_GetAreaAlarmStatusResponse_Sensitivity_tag 4
#define protobuf_GetAreaAlarmStatusResponse_SmartStatus_tag 5
#define protobuf_GetAreaAlarmStatusResponse_SmartType_tag 6
#define protobuf_GetAreaAlarmStatusResponse_Action_tag 7
#define protobuf_GetAreaAlarmStatusResponse_AreaGroup_tag 8
#define protobuf_GetAreaAlarmStatusResponse_ScreenShotStatus_tag 9
#define protobuf_GetAreaAlarmStatusResponse_DefenceStatus_tag 10
#define protobuf_GetAreaAlarmStatusResponse_DefenceTime_tag 11
#define protobuf_GetAreaAlarmStatusResponse_ShowArea_tag 12
#define protobuf_GetEventAlarmOutResponse_Code_tag 1
#define protobuf_GetEventAlarmOutResponse_Message_tag 2
#define protobuf_GetEventAlarmOutResponse_GBAlarmStatus_tag 3
#define protobuf_GetEventAlarmOutResponse_AudioAlarmStatus_tag 4
#define protobuf_GetEventAlarmOutResponse_AudioAlarmFiles_tag 5
#define protobuf_GetEventAlarmOutResponse_AudioPlayCount_tag 6
#define protobuf_GetEventAlarmOutResponse_LightAlarmStatus_tag 7
#define protobuf_GetEventAlarmOutResponse_LightAlarmType_tag 8
#define protobuf_GetEventAlarmOutResponse_LightAlarmFrequency_tag 9
#define protobuf_GetEventAlarmOutResponse_LightAlarmTime_tag 10
#define protobuf_GetLocalStorageConfigResponse_Code_tag 1
#define protobuf_GetLocalStorageConfigResponse_Message_tag 2
#define protobuf_GetLocalStorageConfigResponse_StreamType_tag 3
#define protobuf_GetLocalStorageConfigResponse_StorageType_tag 4
#define protobuf_GetLocalStorageConfigResponse_DefenceTime_tag 5
#define protobuf_GetMDStatusResponse_Code_tag    1
#define protobuf_GetMDStatusResponse_Message_tag 2
#define protobuf_GetMDStatusResponse_EventStatus_tag 3
#define protobuf_GetMDStatusResponse_Sensitivity_tag 4
#define protobuf_GetMDStatusResponse_ScreenShotStatus_tag 5
#define protobuf_GetMDStatusResponse_SmartStatus_tag 6
#define protobuf_GetMDStatusResponse_SmartType_tag 7
#define protobuf_GetMDStatusResponse_DefenceStatus_tag 8
#define protobuf_GetMDStatusResponse_DefenceTime_tag 9
#define protobuf_ImageType_Type_tag              1
#define protobuf_ImageType_Params_tag            2
#define protobuf_NetInfoResponse_Code_tag        1
#define protobuf_NetInfoResponse_Message_tag     2
#define protobuf_NetInfoResponse_NetCards_tag    3
#define protobuf_OSDConfigResponse_Code_tag      1
#define protobuf_OSDConfigResponse_Message_tag   2
#define protobuf_OSDConfigResponse_WeekDisplay_tag 3
#define protobuf_OSDConfigResponse_DateDisplay_tag 4
#define protobuf_OSDConfigResponse_ChannelDisplay_tag 5
#define protobuf_OSDConfigResponse_Channel_tag   6
#define protobuf_OSDConfigResponse_Compositions_tag 7
#define protobuf_SetAreaAlarmStatusRequest_EventStatus_tag 1
#define protobuf_SetAreaAlarmStatusRequest_Sensitivity_tag 2
#define protobuf_SetAreaAlarmStatusRequest_SmartStatus_tag 3
#define protobuf_SetAreaAlarmStatusRequest_SmartType_tag 4
#define protobuf_SetAreaAlarmStatusRequest_Action_tag 5
#define protobuf_SetAreaAlarmStatusRequest_AreaGroup_tag 6
#define protobuf_SetAreaAlarmStatusRequest_ScreenShotStatus_tag 7
#define protobuf_SetAreaAlarmStatusRequest_DefenceStatus_tag 8
#define protobuf_SetAreaAlarmStatusRequest_DefenceTime_tag 9
#define protobuf_SetAreaAlarmStatusRequest_ShowArea_tag 10
#define protobuf_SetAreaAlarmStatusRequest_PresetPosition_tag 11
#define protobuf_SetLocalStorageConfigRequest_StreamType_tag 1
#define protobuf_SetLocalStorageConfigRequest_StorageType_tag 2
#define protobuf_SetLocalStorageConfigRequest_DefenceTime_tag 3
#define protobuf_SetMDStatusRequest_EventStatus_tag 1
#define protobuf_SetMDStatusRequest_Sensitivity_tag 2
#define protobuf_SetMDStatusRequest_ScreenShotStatus_tag 3
#define protobuf_SetMDStatusRequest_SmartStatus_tag 4
#define protobuf_SetMDStatusRequest_SmartType_tag 5
#define protobuf_SetMDStatusRequest_DefenceStatus_tag 6
#define protobuf_SetMDStatusRequest_DefenceTime_tag 7
#define protobuf_SetOSDConfigRequest_ChannelCode_tag 1
#define protobuf_SetOSDConfigRequest_WeekDisplay_tag 2
#define protobuf_SetOSDConfigRequest_DateDisplay_tag 3
#define protobuf_SetOSDConfigRequest_ChannelDisplay_tag 4
#define protobuf_SetOSDConfigRequest_Channel_tag 5
#define protobuf_SetOSDConfigRequest_Compositions_tag 6
#define protobuf_GetImageConfigResponse_Code_tag 1
#define protobuf_GetImageConfigResponse_Message_tag 2
#define protobuf_GetImageConfigResponse_Model_tag 3
#define protobuf_GetImageConfigResponse_Types_tag 4
#define protobuf_SetImageConfigRequest_ChannelCode_tag 1
#define protobuf_SetImageConfigRequest_Model_tag 2
#define protobuf_SetImageConfigRequest_Types_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t protobuf_RegisterRequest_fields[3];
extern const pb_field_t protobuf_RegisterResponseWithNonce_fields[4];
extern const pb_field_t protobuf_RegisterRequestWithAuth_fields[5];
extern const pb_field_t protobuf_RegisterResponse_fields[4];
extern const pb_field_t protobuf_UploadDeviceInfoRequest_fields[8];
extern const pb_field_t protobuf_UploadDeviceInfoResponse_fields[3];
extern const pb_field_t protobuf_Ping_fields[2];
extern const pb_field_t protobuf_Pong_fields[4];
extern const pb_field_t protobuf_DeviceUpdateRequest_fields[7];
extern const pb_field_t protobuf_DeviceUpdateResponse_fields[3];
extern const pb_field_t protobuf_DeviceUpdateNotify_fields[6];
extern const pb_field_t protobuf_OperateResponse_fields[3];
extern const pb_field_t protobuf_GetSDCardInfoRequest_fields[2];
extern const pb_field_t protobuf_GetSDCardInfoResponse_fields[7];
extern const pb_field_t protobuf_FormatSDCardRequest_fields[2];
extern const pb_field_t protobuf_DownLoadStatRequest_fields[3];
extern const pb_field_t protobuf_FromatSDCardStatNotify_fields[3];
extern const pb_field_t protobuf_GetCloudStorageInfoRequest_fields[3];
extern const pb_field_t protobuf_GetCloudStorageInfoResponse_fields[7];
extern const pb_field_t protobuf_CloudStorageInfoChangeNotify_fields[6];
extern const pb_field_t protobuf_GetCloudStorageAddrRequest_fields[8];
extern const pb_field_t protobuf_GetCloudStorageAddrResponse_fields[8];
extern const pb_field_t protobuf_CloudStorageEndNotify_fields[5];
extern const pb_field_t protobuf_GetVideoConfigRequest_fields[3];
extern const pb_field_t protobuf_GetVideoConfigResponse_fields[15];
extern const pb_field_t protobuf_SetVideoConfigRequest_fields[10];
extern const pb_field_t protobuf_GetImageConfigRequest_fields[2];
extern const pb_field_t protobuf_GetImageConfigResponse_fields[5];
extern const pb_field_t protobuf_ImageType_fields[3];
extern const pb_field_t protobuf_ImageParam_fields[3];
extern const pb_field_t protobuf_SetImageConfigRequest_fields[4];
extern const pb_field_t protobuf_DeviceChannelInfoRequest_fields[3];
extern const pb_field_t protobuf_OSDConfigResponse_fields[8];
extern const pb_field_t protobuf_Composition_fields[4];
extern const pb_field_t protobuf_SetOSDConfigRequest_fields[7];
extern const pb_field_t protobuf_GetMDStatusResponse_fields[10];
extern const pb_field_t protobuf_TimeDurationList_fields[3];
extern const pb_field_t protobuf_SetMDStatusRequest_fields[8];
extern const pb_field_t protobuf_GetAreaAlarmStatusRequest_fields[2];
extern const pb_field_t protobuf_GetAreaAlarmStatusResponse_fields[13];
extern const pb_field_t protobuf_Area_fields[3];
extern const pb_field_t protobuf_SetAreaAlarmStatusRequest_fields[12];
extern const pb_field_t protobuf_GetEventAlarmOutRequest_fields[2];
extern const pb_field_t protobuf_GetEventAlarmOutResponse_fields[11];
extern const pb_field_t protobuf_AudioAlarmFile_fields[5];
extern const pb_field_t protobuf_SetEventAlarmOutRequest_fields[10];
extern const pb_field_t protobuf_SetManualAlarmRequest_fields[2];
extern const pb_field_t protobuf_SetAudioAlarmFileRequest_fields[7];
extern const pb_field_t protobuf_AudioAlarmFileUpdateNotify_fields[4];
extern const pb_field_t protobuf_GetNightVisionConfigResponse_fields[6];
extern const pb_field_t protobuf_SetNightLightTypeRequest_fields[2];
extern const pb_field_t protobuf_SetLightnessRequest_fields[2];
extern const pb_field_t protobuf_GetAudioConfigResponse_fields[7];
extern const pb_field_t protobuf_SetAudioConfigRequest_fields[4];
extern const pb_field_t protobuf_GetLocalStorageConfigResponse_fields[6];
extern const pb_field_t protobuf_SetLocalStorageConfigRequest_fields[4];
extern const pb_field_t protobuf_SetEventUploadRequest_fields[4];
extern const pb_field_t protobuf_GetGBConfigResponse_fields[8];
extern const pb_field_t protobuf_UpdateGBConfigRequest_fields[7];
extern const pb_field_t protobuf_GetTimingConfigResponse_fields[5];
extern const pb_field_t protobuf_SetTimingConfigRequest_fields[4];
extern const pb_field_t protobuf_NetInfoResponse_fields[4];
extern const pb_field_t protobuf_NetCardInfo_fields[6];
extern const pb_field_t protobuf_UpdateNetInfoRequest_fields[3];
extern const pb_field_t protobuf_GetDeviceOnvifResponse_fields[5];
extern const pb_field_t protobuf_SetDeviceOnvifRequest_fields[2];

/* Maximum encoded size of messages (where known) */
/* protobuf_RegisterRequest_size depends on runtime parameters */
/* protobuf_RegisterResponseWithNonce_size depends on runtime parameters */
/* protobuf_RegisterRequestWithAuth_size depends on runtime parameters */
/* protobuf_RegisterResponse_size depends on runtime parameters */
/* protobuf_UploadDeviceInfoRequest_size depends on runtime parameters */
/* protobuf_UploadDeviceInfoResponse_size depends on runtime parameters */
#define protobuf_Ping_size                       11
/* protobuf_Pong_size depends on runtime parameters */
/* protobuf_DeviceUpdateRequest_size depends on runtime parameters */
/* protobuf_DeviceUpdateResponse_size depends on runtime parameters */
/* protobuf_DeviceUpdateNotify_size depends on runtime parameters */
/* protobuf_OperateResponse_size depends on runtime parameters */
#define protobuf_GetSDCardInfoRequest_size       11
/* protobuf_GetSDCardInfoResponse_size depends on runtime parameters */
#define protobuf_FormatSDCardRequest_size        11
/* protobuf_DownLoadStatRequest_size depends on runtime parameters */
/* protobuf_FromatSDCardStatNotify_size depends on runtime parameters */
/* protobuf_GetCloudStorageInfoRequest_size depends on runtime parameters */
/* protobuf_GetCloudStorageInfoResponse_size depends on runtime parameters */
/* protobuf_CloudStorageInfoChangeNotify_size depends on runtime parameters */
/* protobuf_GetCloudStorageAddrRequest_size depends on runtime parameters */
/* protobuf_GetCloudStorageAddrResponse_size depends on runtime parameters */
/* protobuf_CloudStorageEndNotify_size depends on runtime parameters */
/* protobuf_GetVideoConfigRequest_size depends on runtime parameters */
/* protobuf_GetVideoConfigResponse_size depends on runtime parameters */
/* protobuf_SetVideoConfigRequest_size depends on runtime parameters */
/* protobuf_GetImageConfigRequest_size depends on runtime parameters */
/* protobuf_GetImageConfigResponse_size depends on runtime parameters */
/* protobuf_ImageType_size depends on runtime parameters */
/* protobuf_ImageParam_size depends on runtime parameters */
/* protobuf_SetImageConfigRequest_size depends on runtime parameters */
/* protobuf_DeviceChannelInfoRequest_size depends on runtime parameters */
/* protobuf_OSDConfigResponse_size depends on runtime parameters */
/* protobuf_Composition_size depends on runtime parameters */
/* protobuf_SetOSDConfigRequest_size depends on runtime parameters */
/* protobuf_GetMDStatusResponse_size depends on runtime parameters */
#define protobuf_TimeDurationList_size           443
#define protobuf_SetMDStatusRequest_size         3221
#define protobuf_GetAreaAlarmStatusRequest_size  11
/* protobuf_GetAreaAlarmStatusResponse_size depends on runtime parameters */
/* protobuf_Area_size depends on runtime parameters */
#define protobuf_SetAreaAlarmStatusRequest_size  (3316 + 3*protobuf_Area_size)
#define protobuf_GetEventAlarmOutRequest_size    11
/* protobuf_GetEventAlarmOutResponse_size depends on runtime parameters */
/* protobuf_AudioAlarmFile_size depends on runtime parameters */
#define protobuf_SetEventAlarmOutRequest_size    99
#define protobuf_SetManualAlarmRequest_size      11
/* protobuf_SetAudioAlarmFileRequest_size depends on runtime parameters */
/* protobuf_AudioAlarmFileUpdateNotify_size depends on runtime parameters */
/* protobuf_GetNightVisionConfigResponse_size depends on runtime parameters */
#define protobuf_SetNightLightTypeRequest_size   11
#define protobuf_SetLightnessRequest_size        11
/* protobuf_GetAudioConfigResponse_size depends on runtime parameters */
#define protobuf_SetAudioConfigRequest_size      33
/* protobuf_GetLocalStorageConfigResponse_size depends on runtime parameters */
#define protobuf_SetLocalStorageConfigRequest_size 3144
/* protobuf_SetEventUploadRequest_size depends on runtime parameters */
/* protobuf_GetGBConfigResponse_size depends on runtime parameters */
/* protobuf_UpdateGBConfigRequest_size depends on runtime parameters */
/* protobuf_GetTimingConfigResponse_size depends on runtime parameters */
/* protobuf_SetTimingConfigRequest_size depends on runtime parameters */
/* protobuf_NetInfoResponse_size depends on runtime parameters */
/* protobuf_NetCardInfo_size depends on runtime parameters */
/* protobuf_UpdateNetInfoRequest_size depends on runtime parameters */
/* protobuf_GetDeviceOnvifResponse_size depends on runtime parameters */
#define protobuf_SetDeviceOnvifRequest_size      11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MOJINGCMD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
