################################################################################
################################################################################
##
## Makefile -- makefile for minirtsp library
##
## (C) Copyright 2012-2014 by Goke Microelectronics Co.,Ltd
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################




LIBRARY = librtspLib

HEADERS +=  $(wildcard src/rtspLib/inc/*.h)
HEADERS +=  $(wildcard src/rtspLib/*.h)
HEADERS +=  $(wildcard src/utilsLib/*.h)
HEADER_SUBDIR = subsystem/minirtsp

SOURCES  += $(wildcard src/rtspLib/*.c)
SOURCES  += $(wildcard src/utilsLib/*.c)

CCFLAGS_USER += -O2
CCFLAGS_USER += -I./inc -Isrc/rtspLib/inc -Isrc/utilsLib/inc
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/subsystem/mediabuffer
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/subsystem/md5
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/subsystem/g711
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/sdk

################################################################################
# define user targets
################################################################################

default: install

clean: clean-objects clean-library clean-all

build:  build-objects build-library install-library

headers: install-headers

install: build install-library install-headers

all: clean build install

################################################################################
# include internal definitions and rules
################################################################################

  RELEASE_SUBDIR = $(SUBDIR)
  RELEASE_FILES += Makefile.rel
  RELEASE_FILES += $(wildcard include/*.h   )
  RELEASE_FILES += Makefile
  RELEASE_FILES += lib/$(LIBRARY)$(LIBRARY_EXT)
  RELEASE_FILES += lib/$(LIBRARY)$(SHARED_EXT)

release: release-lib-prepare  doc release-files $(DIRECTORIES:%=subdir-release-%)

doc:

release-lib-prepare: clean build-library install-release-library
