################################################################################
################################################################################
##
## Makefile -- makefile for api library
##
## (C) Copyright 2012-2014 by Goke Microelectronics Co.,Ltd
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################

LIBRARY = libsdk

include $(TOPDIR)/app/netcam/module_config

HEADERS +=  $(wildcard inc/*.h)
HEADER_SUBDIR = platform/sdk

#SOURCES  += $(wildcard src/*.c)
SOURCES  += src/sdk_common.c
SOURCES  += src/sdk_network.c
SOURCES  += src/sdk.c
SOURCES  += src/sdk_sys.c
SOURCES  += src/sdk_vin.c
SOURCES  += src/sdk_enc.c
SOURCES  += src/sdk_isp.c
SOURCES  += src/sdk_audio.c
SOURCES  += src/sdk_watchdog.c
SOURCES  += src/sdk_gpio.c
SOURCES  += src/sdk_osd.c
SOURCES  += src/sdk_ptz.c
SOURCES  += src/sdk_pwm.c
SOURCES  += src/sdk_pda.c
SOURCES  += src/sdk_vision.c

CCFLAGS_USER += -O2
CCFLAGS_USER += -I inc
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/adi/include    #add
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/image/image_lib/include   #add	
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/subsystem/vision/include
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/subsystem/acodec/aac/libaac/include
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/subsystem/acodec/amr/libamr/include
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/subsystem/eXosip2/include
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/subsystem/minirtsp/inc
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/subsystem/osd/include
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/subsystem/osip2/include
CCFLAGS_USER += -I $(TOPDIR)/platform/sdk/subsystem/osipparser2/include

CCFLAGS_USER += -I $(INSTALL_HEADER_DIR)/adi
CCFLAGS_USER += -I $(INSTALL_HEADER_DIR)/image
CCFLAGS_USER += -I $(INSTALL_HEADER_DIR)/subsystem/vision
ifeq ($(SUPPORT_ECHO_CANCEL),y)
CCFLAGS_USER += -I $(TOPDIR)/app/netcam/inc
CCFLAGS_USER += -I $(INSTALL_HEADER_DIR)/ap
endif
################################################################################
# define user targets
################################################################################

default: install

clean: clean-objects clean-library clean-all

build:  build-objects build-library install-library

headers: install-headers

install: build install-library install-headers

all: clean build install

################################################################################
# include internal definitions and rules
################################################################################

  RELEASE_SUBDIR = $(SUBDIR)
  RELEASE_FILES += Makefile.rel
  RELEASE_FILES += $(wildcard include/*.h   )
  RELEASE_FILES += Makefile
  RELEASE_FILES += lib/$(LIBRARY)$(LIBRARY_EXT)
  RELEASE_FILES += lib/$(LIBRARY)$(SHARED_EXT)

release: release-lib-prepare  doc release-files $(DIRECTORIES:%=subdir-release-%)

doc:

release-lib-prepare: clean build-library install-release-library
