###############################################################################
################################################################################
##
## Makefile -- makefile for wavechannel library
##
## (C) Copyright 2012-2019 by Goke Microelectronics Co.,Ltd
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################



SUBDIR = subsystem/wavechannel

LIBRARY = libwavechannel

#HEADERS += include/*.h
HEADERS += rs_codec/*.h
HEADERS += interface/*.h
HEADERS += proto_utils/*.h
HEADER_SUBDIR = subsystem/wavechannel

SOURCES  += ./buff_utils/queue.c  
SOURCES  += ./buff_utils/ring_buff.c  
SOURCES  += ./checksum_utils/crc_codec.c  
SOURCES  += ./checksum_utils/parity_codec.c  
SOURCES  += ./kiss_fft/kiss_fastfir.c  
SOURCES  += ./kiss_fft/kiss_fft.c  
SOURCES  += ./kiss_fft/kiss_fftr.c  
SOURCES  += ./log_utils/wt_log.c  
SOURCES  += ./proto_utils/wt_proto_common.c  
SOURCES  += ./proto_utils/wt_proto_link_layer.c  
SOURCES  += ./proto_utils/wt_proto_physical_layer.c  
SOURCES  += ./transceiver/recv/wt_recv_link_layer.c  
SOURCES  += ./transceiver/recv/wt_recv_physical_layer.c  
#SOURCES  += ./transceiver/send/wt_send_link_layer.c  
#SOURCES  += ./transceiver/send/wt_send_physical_layer.c  
SOURCES  += ./interface/wave_trans_recv.c  
#SOURCES  += ./interface/wave_trans_send.c  
SOURCES  += ./audio_codec/pcm_to_wav.c
#SOURCES  += ./rs_codec/rs_code.c

CCFLAGS_USER += -O2
#CCFLAGS_USER += -mfpu=vfp -mfloat-abi=softfp -ffast-math	//xqq
CCFLAGS_USER += -ffast-math
CCFLAGS_USER += -I include
CCFLAGS_USER += -I $(SDK_TOP)/adi/include
CCFLAGS_USER += -I ./
CCFLAGS_USER += -I ./interface
CCFLAGS_USER += -I ./proto_utils


################################################################################
# define user targets
################################################################################

default: install

clean: clean-objects clean-library clean-all

build:  build-objects build-library install-library

headers: install-headers

install: build install-library install-headers

all: clean build install

################################################################################
# include internal definitions and rules
################################################################################

  RELEASE_SUBDIR = $(SUBDIR)
  RELEASE_FILES += $(SOURCES)
  RELEASE_FILES += $(wildcard include/*.h   )
  RELEASE_FILES += Makefile

release: doc release-files

doc:
