################################################################################
################################################################################
##
## Makefile -- makefile for tuning library
##
## (C) Copyright 2012-2014 by Goke Microelectronics Co.,Ltd
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################

LIBRARY = libmail

HEADERS +=  $(wildcard inc/*.h)
HEADER_SUBDIR = subsystem/mail

SOURCES  += src/Base64.c src/list.c src/Ssmtp.c

CCFLAGS_USER += -DHAVE_SSL
CCFLAGS_USER += -O2
CCFLAGS_USER += -I inc
CCFLAGS_USER += -I openssl/include
CCFLAGS_USER += -I src
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/subsystem/mail
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/subsystem/utility
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/sdk

################################################################################
# define user targets
################################################################################

default: install

clean: clean-objects clean-library clean-all

build:  build-objects build-library install-library install-openssl

headers: install-headers install-headers-openssl

install: build install-library install-headers

all: clean build install

install-openssl:
	cp ./openssl/lib/*.a $(INSTALL_LIBRARY_DIR)
install-headers-openssl:
	cp ./openssl/include/openssl $(INSTALL_DIR)/$(INSTALL_INCLUDE_SUBDIR) -Rf

################################################################################
# include internal definitions and rules
################################################################################

  RELEASE_SUBDIR = $(SUBDIR)
  RELEASE_FILES += Makefile.rel
  RELEASE_FILES += $(wildcard include/*.h   )
  RELEASE_FILES += Makefile
  RELEASE_FILES += lib/$(LIBRARY)$(LIBRARY_EXT)
  RELEASE_FILES += lib/$(LIBRARY)$(SHARED_EXT)

release: release-lib-prepare  doc release-files $(DIRECTORIES:%=subdir-release-%)

doc:

release-lib-prepare: clean build-library install-release-library
