################################################################################
################################################################################
##
## Makefile -- makefile for OSD library
##
## (C) Copyright 2012-2014 by Goke Microelectronics Co.,Ltd
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################
include ../../app/netcam/module_config
ifeq ($(SUPPORT_VECTOR_FONT),y)
FREETYPE_DIR = $(FILESYSTEM_DIR)/oss-prebuild-$(shell echo $(DECODER)|tr A-Z a-z)-$(C_LIBRARY)/freetype
endif

LIBRARY = libosd

HEADERS +=  $(wildcard inc/*.h)
HEADER_SUBDIR = subsystem/osd

SOURCES  += src/canvas.c
ifeq ($(SUPPORT_VECTOR_FONT),y)
SOURCES  += src/utf8_to_unicode.c
SOURCES  += src/osd_vector_font.c
else
SOURCES  += src/osd_font.c
endif
SOURCES  += src/osd.c

CCFLAGS_USER += -O2
CCFLAGS_USER += -I src -I inc
CCFLAGS_USER += -I ../../platform/api/inc	#add
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/platform/sdk
ifeq ($(SUPPORT_VECTOR_FONT),y)
CCFLAGS_USER += -I $(FREETYPE_DIR)/include/freetype2
endif
################################################################################
# define user targets
################################################################################

default: install

clean: clean-objects clean-library clean-all
ifeq ($(SUPPORT_VECTOR_FONT),y)
build: build-pre-library build-objects build-library install-library
else
build:  build-objects build-library install-library
endif
headers: install-headers

install: build install-library install-headers
#	@cp -a ./build/arm11-gcc-linux-GK7101/lib/$(LIBRARY).so $(ROOTFS_TOP)/usr/lib

all: clean build install
ifeq ($(SUPPORT_VECTOR_FONT),y)
build-pre-library:
	@cp -a $(FREETYPE_DIR)/lib/*.a $(INSTALL_LIBRARY_DIR)
endif
################################################################################
# include internal definitions and rules
################################################################################

  RELEASE_SUBDIR = $(SUBDIR)
  RELEASE_FILES += Makefile.rel
  RELEASE_FILES += $(wildcard include/*.h   )
  RELEASE_FILES += Makefile
  RELEASE_FILES += lib/$(LIBRARY)$(LIBRARY_EXT)
  RELEASE_FILES += lib/$(LIBRARY)$(SHARED_EXT)

release: release-lib-prepare  doc release-files $(DIRECTORIES:%=subdir-release-%)

doc:

release-lib-prepare: clean build-library install-release-library
