################################################################################
################################################################################
##
## Makefile -- makefile for tuning library
##
## (C) Copyright 2012-2014 by Goke Microelectronics Co.,Ltd
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################




LIBRARY = libhttpserver

HEADERS +=  $(wildcard inc/*.h)
HEADER_SUBDIR = subsystem/http

SOURCES  += src/http_class.c src/http_const.c src/http_decode.c src/http_encode.c \
src/http_list.c src/http_llist.c src/http_main.c src/http_process_thread.c \
src/http_read_thread.c src/http_write_thread.c src/http_compress.c src/static_memory_pool.c \
src/entry_queue.c src/lf_thread_pool.c src/http_utils.c


CCFLAGS_USER += -O2
CCFLAGS_USER += -I inc
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/subsystem/zlib
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/sdk

################################################################################
# define user targets
################################################################################

default: install

clean: clean-objects clean-library clean-all

build:  build-objects build-library install-library

headers: install-headers

install: build install-library install-headers

all: clean build install

################################################################################
# include internal definitions and rules
################################################################################

  RELEASE_SUBDIR = $(SUBDIR)
  RELEASE_FILES += Makefile.rel
  RELEASE_FILES += $(wildcard include/*.h   )
  RELEASE_FILES += Makefile
  RELEASE_FILES += lib/$(LIBRARY)$(LIBRARY_EXT)
  RELEASE_FILES += lib/$(LIBRARY)$(SHARED_EXT)

release: release-lib-prepare  doc release-files $(DIRECTORIES:%=subdir-release-%)

doc:

release-lib-prepare: clean build-library install-release-library
