################################################################################
################################################################################
##
## Makefile -- makefile for tuning library
##
## (C) Copyright 2012-2014 by Goke Microelectronics Co.,Ltd
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################




LIBRARY = libwctl

HEADERS +=  $(wildcard include/*.h)
HEADER_SUBDIR = subsystem/wireless

SOURCES += ./src/net_utils.c
SOURCES += ./src/net_wifi_sta.c
SOURCES += ./src/net_wifi_commom.c
SOURCES += ./src/net_wifi_host.c
SOURCES += ./src/net_wifi_wpa.c
SOURCES += ./src/net_wifi_smartlink.c
SOURCES += ./src/network_wifi.c
SOURCES += ./src/zbar_qrcodelink.c
SOURCES += ./src/net_ping.c
SOURCES += ./src/net_gateway.c
CCFLAGS_USER += -O2
CCFLAGS_USER += -I include
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/platform/sdk
CCFLAGS_USER += -I$(INSTALL_HEADER_DIR)/subsystem/zbar

ifeq ($(SUPPORT_AP_STA),y)
CCFLAGS_USER += -DAP_STA_SUPPORT
endif
################################################################################
# define user targets
################################################################################

default: install

clean: clean-objects clean-library clean-all

build:  build-objects build-library install-library

headers: install-headers

install: build install-library install-headers

all: clean build install
	echo CCFLAGS_USERxx=$(CCFLAGS_USER)
################################################################################
# include internal definitions and rules
################################################################################

  RELEASE_SUBDIR = $(SUBDIR)
  RELEASE_FILES += Makefile.rel
  RELEASE_FILES += $(wildcard include/*.h   )
  RELEASE_FILES += Makefile
  RELEASE_FILES += lib/$(LIBRARY)$(LIBRARY_EXT)
  RELEASE_FILES += lib/$(LIBRARY)$(SHARED_EXT)

release: release-lib-prepare  doc release-files $(DIRECTORIES:%=subdir-release-%)

doc:

release-lib-prepare: clean build-library install-release-library
