################################################################################
################################################################################
##
## Kbuild -- Kbuild for sp2307_ex module
##
## (C) Copyright 2012-2015 by GOKE MICROELECTRONICS Co.,Ltd
##
################################################################################
################################################################################

EXTRA_CFLAGS        += $(PRIVATE_CFLAGS)
EXTRA_AFLAGS        += $(PRIVATE_AFLAGS)
EXTRA_LDFLAGS       += $(PRIVATE_LDFLAGS)
EXTRA_ARFLAGS       += $(PRIVATE_ARFLAGS)

    obj-m := sp2307_ex.o

