#include "http_const.h"
#include "http_export.h"

/*http standard error code*/
const char* http_error[] = 
{
/* 0  */ "100 Continue",
/* 1  */	"101 Switching Protocols",
/* 2  */	"200 OK",
/* 3  */	"201 Created",
/* 4  */	"202 Accepted",
/* 5  */	"203 Partial Information",
/* 6  */	"204 No Content",
/* 7  */	"205 Reset Content",
/* 8  */	"206 Partial Content",
/* 9  */	"300 Multiple Choices",
/* 10 */	"301 Moved Permanently",
/* 11 */	"302 Moved Temporarily",
/* 12 */	"303 See Other",
/* 13 */	"304 Not Modified",
/* 14 */	"305 Use Proxy",
/* 15 */	"400 Bad Request",
/* 16 */	"401 Unauthorized",
/* 17 */	"402 Payment Required",
/* 18 */	"403 Forbidden",
/* 19 */	"404 Not Found",
/* 20 */	"405 Method Not Allowed",
/* 21 */	"406 Not Acceptable",
/* 22 */	"407 Proxy Authentication Required",
/* 23 */	"408 Request Time-Out",
/* 24 */	"409 Conflict",
/* 25 */	"410 Gone",
/* 26 */	"411 Length Required",
/* 27 */	"412 Precondition Failed",
/* 28 */	"413 Request Entity Too Large",
/* 29 */	"414 Request-URL Too Large",
/* 30 */	"415 Unsupported Media Type",
/* 31 */	"500 Server Error",
/* 32 */	"501 Not Implemented",
/* 33 */	"502 Bad Gateway",
/* 34 */	"503 Out of Resources",
/* 35 */	"504 Gateway Time-Out",
/* 36 */	"505 HTTP Version not supported"
};


/*Content type*/
const char* file_suffix[] = 
{
	".cgi", 
	".html", 
/*************/
	".*",
	".001",
	".323",
	".907",
	".acp",
	".aif",
	".aiff",
	".asa",
	".asp",
	".au",
	".awf",
	".bmp",
	".c4t",
	".cal",
	".cdf",
	".cel",
	".cg4",
	".cit",
	".cml",
	".cmx",
	".crl",
	".csi",
	".cut",
	".dbm",
	".dcd",
	".der",
	".dib",
	".doc",
	".drw",
	".dwf",
	".dwg",
	".dxf",
	".emf",
	".ent",
	".etd",
	".fax",
	".fif",
	".frm",
	".gbr",
	".gif",
	".gp4",
	".hmr",
	".hpl",
	".hrf",
	".htc",
	".htx",
	".ico",
	".iff",
	".igs",
	".img",
	".isp",
	".java",
	".jpe",
	".jpeg",
	".jsp",
	".lar",
	".lavs",
	".lmsff",
	".ltr",
	".m2v",
	".m4e",
	".man",
	".mfp",
	".mhtml",
	".mid",
	".mil",
	".mnd",
	".mocha",
	".mp1",
	".mp2v",
	".mp4",
	".mpd",
	".mpeg",
	".mpga",
	".mps",
	".mpv",
	".mpw",
	".mtx",
	".net",
	".nws",
	".out",
	".p12",
	".p7c",
	".p7r",
	".pc5",
	".pcl",
	".pdf",
	".pdx",
	".pgl",
	".pko",
	".plg",
	".plt",
	".ppa",
	".pps",
	".ppt",
	".prf",
	".prt",
	".ps",
	".pwz",
	".ra",
	".ras",
	".rdf",
	".red",
	".rjs",
	".rlc",
	".rm",
	".rmi",
	".rmm",
	".rms",
	".rmx",
	".rp",
	".rsml",
	".rv",
	".sat",
	".sdw",
	".slb",
	".slk",
	".smil",
	".snd",
	".sor",
	".spl",
	".ssm",
	".stl",
	".sty",
	".swf",
	".tg4",
	".tif",
	".tiff",
	".top",
	".tsd",
	".uin",
	".vcf",
	".vdx",
	".vpg",
	".vsd",
	".vsw",
	".vtx",
	".wav",
	".wb1",
	".wb3",
	".wiz",
	".wk4",
	".wks",
	".wma",
	".wmf",
	".wmv",
	".wmz",
	".wpd",
	".wpl",
	".wr1",
	".wrk",
	".ws2",
	".wsdl",
	".xdp",
	".xfd",
	".xhtml",
	".xls",
	".xml",
	".xq",
	".xquery",
	".xsl",
	".xwd",
	".sis",
	".x_t",
	".apk",
	".301",
	".906",
	".a11",
	".ai",
	".aifc",
	".anv",
	".asf",
	".asx",
	".avi",
	".biz",
	".bot",
	".c90",
	".cat",
	".cdr",
	".cer",
	".cgm",
	".class",
	".cmp",
	".cot",
	".crt",
	".css",
	".dbf",
	".dbx",
	".dcx",
	".dgn",
	".dll",
	".dot",
	".dtd",
	".dxb",
	".edn",
	".eml",
	".epi",
	".eps",
	".exe",
	".fdf",
	".fo",
	".g4",
	".",
	".gl2",
	".hgl",
	".hpg",
	".hqx",
	".hta",
	".htm",
	".htt",
	".icb",
	".ig4",
	".iii",
	".ins",
	".IVF",
	".jfif",
	".jpg",
	".js",
	".la1",
	".latex",
	".lbm",
	".ls",
	".m1v",
	".m3u",
	".mac",
	".math",
	".mdb",
	".mht",
	".mi",
	".midi",
	".mml",
	".mns",
	".movie",
	".mp2",
	".mp3",
	".mpa",
	".mpe",
	".mpg",
	".mpp",
	".mpt",
	".mpv2",
	".mpx",
	".mxp",
	".nrf",
	".odc",
	".p10",
	".p7b",
	".p7m",
	".p7s",
	".pci",
	".pcx",
	".pdf",
	".pfx",
	".pic",
	".pl",
	".pls",
	".png",
	".pot",
	".ppm",
	".pr",
	".prn",
	".ptn",
	".r3t",
	".ram",
	".rat",
	".rec",
	".rgb",
	".rjt",
	".rle",
	".rmf",
	".rmj",
	".rmp",
	".rmvb",
	".rnx",
	".rpm",
	".rt",
	".rtf",
	".sam",
	".sdp",
	".sit",
	".sld",
	".smi",
	".smk",
	".sol",
	".spc",
	".spp",
	".sst",
	".stm",
	".svg",
	".tdf",
	".tga",
	".tld",
	".torrent",
	".txt",
	".uls",
	".vda",
	".vml",
	".vss",
	".vst",
	".vsx",
	".vxml",
	".wax",
	".wb2",
	".wbmp",
	".wk3",
	".wkq",
	".wm",
	".wmd",
	".wml",
	".wmx",
	".wp6",
	".wpg",
	".wq1",
	".wri",
	".ws",
	".wsc",
	".wvx",
	".xdr",
	".xfdf",
	".xlw",
	".xpl",
	".xql",
	".xsd",
	".xslt",
	".x_b",
	".sisx",
	".ipa",
	".xap",
	".rar",
	".cab",
	".nmf",
	".pexe",

	0
};


const char* content_type[] = {
/*    .cgi     */    "text/html",
/*    .html    */    "text/html",
/*    .*       */    "application/octet-stream",
/*    .001     */    "application/x-001",
/*    .323     */    "text/h323",
/*    .907     */    "drawing/907",
/*    .acp     */    "audio/x-mei-aac",
/*    .aif     */    "audio/aiff",
/*    .aiff    */    "audio/aiff",
/*    .asa     */    "text/asa",
/*    .asp     */    "text/asp",
/*    .au      */    "audio/basic",
/*    .awf     */    "application/vnd.adobe.workflow",
/*    .bmp     */    "application/x-bmp",
/*    .c4t     */    "application/x-c4t",
/*    .cal     */    "application/x-cals",
/*    .cdf     */    "application/x-netcdf",
/*    .cel     */    "application/x-cel",
/*    .cg4     */    "application/x-g4",
/*    .cit     */    "application/x-cit",
/*    .cml     */    "text/xml",
/*    .cmx     */    "application/x-cmx",
/*    .crl     */    "application/pkix-crl",
/*    .csi     */    "application/x-csi",
/*    .cut     */    "application/x-cut",
/*    .dbm     */    "application/x-dbm",
/*    .dcd     */    "text/xml",
/*    .der     */    "application/x-x509-ca-cert",
/*    .dib     */    "application/x-dib",
/*    .doc     */    "application/msword",
/*    .drw     */    "application/x-drw",
/*    .dwf     */    "Model/vnd.dwf",
/*    .dwg     */    "application/x-dwg",
/*    .dxf     */    "application/x-dxf",
/*    .emf     */    "application/x-emf",
/*    .ent     */    "text/xml",
/*    .etd     */    "application/x-ebx",
/*    .fax     */    "image/fax",
/*    .fif     */    "application/fractals",
/*    .frm     */    "application/x-frm",
/*    .gbr     */    "application/x-gbr",
/*    .gif     */    "image/gif",
/*    .gp4     */    "application/x-gp4",
/*    .hmr     */    "application/x-hmr",
/*    .hpl     */    "application/x-hpl",
/*    .hrf     */    "application/x-hrf",
/*    .htc     */    "text/x-component",
/*    .htx     */    "text/html",
/*    .ico     */    "image/x-icon",
/*    .iff     */    "application/x-iff",
/*    .igs     */    "application/x-igs",
/*    .img     */    "application/x-img",
/*    .isp     */    "application/x-internet-signup",
/*    .java    */    "java/*",
/*    .jpe     */    "image/jpeg",
/*    .jpeg    */    "image/jpeg",
/*    .jsp     */    "text/html",
/*    .lar     */    "application/x-laplayer-reg",
/*    .lavs    */    "audio/x-liquid-secure",
/*    .lmsff   */    "audio/x-la-lms",
/*    .ltr     */    "application/x-ltr",
/*    .m2v     */    "video/x-mpeg",
/*    .m4e     */    "video/mpeg4",
/*    .man     */    "application/x-troff-man",
/*    .mfp     */    "application/x-shockwave-flash",
/*    .mhtml   */    "message/rfc822",
/*    .mid     */    "audio/mid",
/*    .mil     */    "application/x-mil",
/*    .mnd     */    "audio/x-musicnet-download",
/*    .mocha   */    "application/x-javascript",
/*    .mp1     */    "audio/mp1",
/*    .mp2v    */    "video/mpeg",
/*    .mp4     */    "video/mpeg4",
/*    .mpd     */    "application/vnd.ms-project",
/*    .mpeg    */    "video/mpg",
/*    .mpga    */    "audio/rn-mpeg",
/*    .mps     */    "video/x-mpeg",
/*    .mpv     */    "video/mpg",
/*    .mpw     */    "application/vnd.ms-project",
/*    .mtx     */    "text/xml",
/*    .net     */    "image/pnetvue",
/*    .nws     */    "message/rfc822",
/*    .out     */    "application/x-out",
/*    .p12     */    "application/x-pkcs12",
/*    .p7c     */    "application/pkcs7-mime",
/*    .p7r     */    "application/x-pkcs7-certreqresp",
/*    .pc5     */    "application/x-pc5",
/*    .pcl     */    "application/x-pcl",
/*    .pdf     */    "application/pdf",
/*    .pdx     */    "application/vnd.adobe.pdx",
/*    .pgl     */    "application/x-pgl",
/*    .pko     */    "application/vnd.ms-pki.pko",
/*    .plg     */    "text/html",
/*    .plt     */    "application/x-plt",
/*    .ppa     */    "application/vnd.ms-powerpoint",
/*    .pps     */    "application/vnd.ms-powerpoint",
/*    .ppt     */    "application/x-ppt",
/*    .prf     */    "application/pics-rules",
/*    .prt     */    "application/x-prt",
/*    .ps      */    "application/postscript",
/*    .pwz     */    "application/vnd.ms-powerpoint",
/*    .ra      */    "audio/vnd.rn-realaudio",
/*    .ras     */    "application/x-ras",
/*    .rdf     */    "text/xml",
/*    .red     */    "application/x-red",
/*    .rjs     */    "application/vnd.rn-realsystem-rjs",
/*    .rlc     */    "application/x-rlc",
/*    .rm      */    "application/vnd.rn-realmedia",
/*    .rmi     */    "audio/mid",
/*    .rmm     */    "audio/x-pn-realaudio",
/*    .rms     */    "application/vnd.rn-realmedia-secure",
/*    .rmx     */    "application/vnd.rn-realsystem-rmx",
/*    .rp      */    "image/vnd.rn-realpix",
/*    .rsml    */    "application/vnd.rn-rsml",
/*    .rv      */    "video/vnd.rn-realvideo",
/*    .sat     */    "application/x-sat",
/*    .sdw     */    "application/x-sdw",
/*    .slb     */    "application/x-slb",
/*    .slk     */    "drawing/x-slk",
/*    .smil    */    "application/smil",
/*    .snd     */    "audio/basic",
/*    .sor     */    "text/plain",
/*    .spl     */    "application/futuresplash",
/*    .ssm     */    "application/streamingmedia",
/*    .stl     */    "application/vnd.ms-pki.stl",
/*    .sty     */    "application/x-sty",
/*    .swf     */    "application/x-shockwave-flash",
/*    .tg4     */    "application/x-tg4",
/*    .tif     */    "image/tiff",
/*    .tiff    */    "image/tiff",
/*    .top     */    "drawing/x-top",
/*    .tsd     */    "text/xml",
/*    .uin     */    "application/x-icq",
/*    .vcf     */    "text/x-vcard",
/*    .vdx     */    "application/vnd.visio",
/*    .vpg     */    "application/x-vpeg005",
/*    .vsd     */    "application/x-vsd",
/*    .vsw     */    "application/vnd.visio",
/*    .vtx     */    "application/vnd.visio",
/*    .wav     */    "audio/wav",
/*    .wb1     */    "application/x-wb1",
/*    .wb3     */    "application/x-wb3",
/*    .wiz     */    "application/msword",
/*    .wk4     */    "application/x-wk4",
/*    .wks     */    "application/x-wks",
/*    .wma     */    "audio/x-ms-wma",
/*    .wmf     */    "application/x-wmf",
/*    .wmv     */    "video/x-ms-wmv",
/*    .wmz     */    "application/x-ms-wmz",
/*    .wpd     */    "application/x-wpd",
/*    .wpl     */    "application/vnd.ms-wpl",
/*    .wr1     */    "application/x-wr1",
/*    .wrk     */    "application/x-wrk",
/*    .ws2     */    "application/x-ws",
/*    .wsdl    */    "text/xml",
/*    .xdp     */    "application/vnd.adobe.xdp",
/*    .xfd     */    "application/vnd.adobe.xfd",
/*    .xhtml   */    "text/html",
/*    .xls     */    "application/x-xls",
/*    .xml     */    "text/xml",
/*    .xq      */    "text/xml",
/*    .xquery  */    "text/xml",
/*    .xsl     */    "text/xml",
/*    .xwd     */    "application/x-xwd",
/*    .sis     */    "application/vnd.symbian.install",
/*    .x_t     */    "application/x-x_t",
/*    .apk     */    "application/vnd.android.package-archive",
/*    .301     */    "application/x-301",
/*    .906     */    "application/x-906",
/*    .a11     */    "application/x-a11",
/*    .ai      */    "application/postscript",
/*    .aifc    */    "audio/aiff",
/*    .anv     */    "application/x-anv",
/*    .asf     */    "video/x-ms-asf",
/*    .asx     */    "video/x-ms-asf",
/*    .avi     */    "video/avi",
/*    .biz     */    "text/xml",
/*    .bot     */    "application/x-bot",
/*    .c90     */    "application/x-c90",
/*    .cat     */    "application/vnd.ms-pki.seccat",
/*    .cdr     */    "application/x-cdr",
/*    .cer     */    "application/x-x509-ca-cert",
/*    .cgm     */    "application/x-cgm",
/*    .class   */    "java/*",
/*    .cmp     */    "application/x-cmp",
/*    .cot     */    "application/x-cot",
/*    .crt     */    "application/x-x509-ca-cert",
/*    .css     */    "text/css",
/*    .dbf     */    "application/x-dbf",
/*    .dbx     */    "application/x-dbx",
/*    .dcx     */    "application/x-dcx",
/*    .dgn     */    "application/x-dgn",
/*    .dll     */    "application/x-msdownload",
/*    .dot     */    "application/msword",
/*    .dtd     */    "text/xml",
/*    .dxb     */    "application/x-dxb",
/*    .edn     */    "application/vnd.adobe.edn",
/*    .eml     */    "message/rfc822",
/*    .epi     */    "application/x-epi",
/*    .eps     */    "application/postscript",
/*    .exe     */    "application/x-msdownload",
/*    .fdf     */    "application/vnd.fdf",
/*    .fo      */    "text/xml",
/*    .g4      */    "application/x-g4",
/*    .        */    "application/x-",
/*    .gl2     */    "application/x-gl2",
/*    .hgl     */    "application/x-hgl",
/*    .hpg     */    "application/x-hpgl",
/*    .hqx     */    "application/mac-binhex40",
/*    .hta     */    "application/hta",
/*    .htm     */    "text/html",
/*    .htt     */    "text/webviewhtml",
/*    .icb     */    "application/x-icb",
/*    .ig4     */    "application/x-g4",
/*    .iii     */    "application/x-iphone",
/*    .ins     */    "application/x-internet-signup",
/*    .IVF     */    "video/x-ivf",
/*    .jfif    */    "image/jpeg",
/*    .jpg     */    "image/jpeg",
/*    .js      */    "application/javascript",
/*    .la1     */    "audio/x-liquid-file",
/*    .latex   */    "application/x-latex",
/*    .lbm     */    "application/x-lbm",
/*    .ls      */    "application/x-javascript",
/*    .m1v     */    "video/x-mpeg",
/*    .m3u     */    "audio/mpegurl",
/*    .mac     */    "application/x-mac",
/*    .math    */    "text/xml",
/*    .mdb     */    "application/x-mdb",
/*    .mht     */    "message/rfc822",
/*    .mi      */    "application/x-mi",
/*    .midi    */    "audio/mid",
/*    .mml     */    "text/xml",
/*    .mns     */    "audio/x-musicnet-stream",
/*    .movie   */    "video/x-sgi-movie",
/*    .mp2     */    "audio/mp2",
/*    .mp3     */    "audio/mp3",
/*    .mpa     */    "video/x-mpg",
/*    .mpe     */    "video/x-mpeg",
/*    .mpg     */    "video/mpg",
/*    .mpp     */    "application/vnd.ms-project",
/*    .mpt     */    "application/vnd.ms-project",
/*    .mpv2    */    "video/mpeg",
/*    .mpx     */    "application/vnd.ms-project",
/*    .mxp     */    "application/x-mmxp",
/*    .nrf     */    "application/x-nrf",
/*    .odc     */    "text/x-ms-odc",
/*    .p10     */    "application/pkcs10",
/*    .p7b     */    "application/x-pkcs7-certificates",
/*    .p7m     */    "application/pkcs7-mime",
/*    .p7s     */    "application/pkcs7-signature",
/*    .pci     */    "application/x-pci",
/*    .pcx     */    "application/x-pcx",
/*    .pdf     */    "application/pdf",
/*    .pfx     */    "application/x-pkcs12",
/*    .pic     */    "application/x-pic",
/*    .pl      */    "application/x-perl",
/*    .pls     */    "audio/scpls",
/*    .png     */    "image/png",
/*    .pot     */    "application/vnd.ms-powerpoint",
/*    .ppm     */    "application/x-ppm",
/*    .pr      */    "application/x-pr",
/*    .prn     */    "application/x-prn",
/*    .ptn     */    "application/x-ptn",
/*    .r3t     */    "text/vnd.rn-realtext3d",
/*    .ram     */    "audio/x-pn-realaudio",
/*    .rat     */    "application/rat-file",
/*    .rec     */    "application/vnd.rn-recording",
/*    .rgb     */    "application/x-rgb",
/*    .rjt     */    "application/vnd.rn-realsystem-rjt",
/*    .rle     */    "application/x-rle",
/*    .rmf     */    "application/vnd.adobe.rmf",
/*    .rmj     */    "application/vnd.rn-realsystem-rmj",
/*    .rmp     */    "application/vnd.rn-rn_music_package",
/*    .rmvb    */    "application/vnd.rn-realmedia-vbr",
/*    .rnx     */    "application/vnd.rn-realplayer",
/*    .rpm     */    "audio/x-pn-realaudio-plugin",
/*    .rt      */    "text/vnd.rn-realtext",
/*    .rtf     */    "application/x-rtf",
/*    .sam     */    "application/x-sam",
/*    .sdp     */    "application/sdp",
/*    .sit     */    "application/x-stuffit",
/*    .sld     */    "application/x-sld",
/*    .smi     */    "application/smil",
/*    .smk     */    "application/x-smk",
/*    .sol     */    "text/plain",
/*    .spc     */    "application/x-pkcs7-certificates",
/*    .spp     */    "text/xml",
/*    .sst     */    "application/vnd.ms-pki.certstore",
/*    .stm     */    "text/html",
/*    .svg     */    "text/xml",
/*    .tdf     */    "application/x-tdf",
/*    .tga     */    "application/x-tga",
/*    .tld     */    "text/xml",
/*    .torrent */    "application/x-bittorrent",
/*    .txt     */    "text/plain",
/*    .uls     */    "text/iuls",
/*    .vda     */    "application/x-vda",
/*    .vml     */    "text/xml",
/*    .vss     */    "application/vnd.visio",
/*    .vst     */    "application/x-vst",
/*    .vsx     */    "application/vnd.visio",
/*    .vxml    */    "text/xml",
/*    .wax     */    "audio/x-ms-wax",
/*    .wb2     */    "application/x-wb2",
/*    .wbmp    */    "image/vnd.wap.wbmp",
/*    .wk3     */    "application/x-wk3",
/*    .wkq     */    "application/x-wkq",
/*    .wm      */    "video/x-ms-wm",
/*    .wmd     */    "application/x-ms-wmd",
/*    .wml     */    "text/vnd.wap.wml",
/*    .wmx     */    "video/x-ms-wmx",
/*    .wp6     */    "application/x-wp6",
/*    .wpg     */    "application/x-wpg",
/*    .wq1     */    "application/x-wq1",
/*    .wri     */    "application/x-wri",
/*    .ws      */    "application/x-ws",
/*    .wsc     */    "text/scriptlet",
/*    .wvx     */    "video/x-ms-wvx",
/*    .xdr     */    "text/xml",
/*    .xfdf    */    "application/vnd.adobe.xfdf",
/*    .xlw     */    "application/x-xlw",
/*    .xpl     */    "audio/scpls",
/*    .xql     */    "text/xml",
/*    .xsd     */    "text/xml",
/*    .xslt    */    "text/xml",
/*    .x_b     */    "application/x-x_b",
/*    .sisx    */    "application/vnd.symbian.install",
/*    .ipa     */    "application/vnd.iphone",
/*    .xap     */    "application/x-silverlight-app",
/*    .rar      */    "application/x-rar-compressed",
/*    .cab     */    "application/vnd.ms-cab-compressed"
/*    .nmf     */    "nmf file"
/*    .pexe     */    "pexe file"
};


int error_code_mapping(int ret)
{
	int error_code;
	
	switch (ret)
	{
	case HPE_OK:
		error_code = HTTP_STATUS_OK;
		break;
		
	/*call back return value*/
	case HPE_RET_FAIL:
		error_code = HTTP_STATUS_NotFound;
		break;

	case HPE_RET_OUTOF_MEMORY:
		error_code = HTTP_STATUS_OutOfResources;
		break;

	case HPE_RET_UNAUTHORIZED:
		error_code = HTTP_STATUS_Unauthorized;
		break;

	/*http server inner function return value*/
	case -HPE_NO_HANDLE_FUNC:
		error_code = HTTP_STATUS_NotImplemented;
		break;

	case -HPE_INVALID_METHOD:
		error_code = HTTP_STATUS_MethodNotAllowed;
		break;

	case -HPE_MALLOC_FAIL:
		error_code = HTTP_STATUS_OutOfResources;
		break;

	case -HPE_INVALID_VERSION:
		error_code = HTTP_STATUS_VersionNotSupported;
		break;

	case -HPE_READ_FILE_FAIL:
	case -HPE_FILE_NOT_EXIST:
		error_code = HTTP_STATUS_NotFound;
		break;

	case -HPE_HEADER_OVERFLOW:
		error_code = HTTP_STATUS_RequestEntityTooLarge;
		break;

	case -HPE_INVALID_EOF_STATE:
	case -HPE_CLOSED_CONNECTION:
	case -HPE_INVALID_STATUS:
	case -HPE_INVALID_URL:
	case -HPE_INVALID_HOST:
	case -HPE_INVALID_PORT:
	case -HPE_INVALID_PATH:
	case -HPE_INVALID_QUERY_STRING:
	case -HPE_INVALID_FRAGMENT:
	case -HPE_LF_EXPECTED:
	case -HPE_INVALID_HEADER_TOKEN:
	case -HPE_INVALID_CONTENT_LENGTH:
	case -HPE_INVALID_CHUNK_SIZE:
	case -HPE_INVALID_CONSTANT:
	case -HPE_INVALID_INTERNAL_STATE:
	case -HPE_STRICT:
	case -HPE_PAUSED:
	case -HPE_UNKNOWN:
		error_code = HTTP_STATUS_BadRequest;
		break;

	case -HPE_RECV_PACKET_FAIL:
		error_code = HTTP_STATUS_ServerError;
		break;
	/************** Add by Ludy, please Teng xiaozhou check ************/	
	case -HPE_RECOURCE_NOT_MODIFIED:
		error_code = HTTP_STATUS_NotModified;
		break;
	/************** Add by Ludy, please Teng xiaozhou check ************/		
	default:
		error_code = HTTP_STATUS_NotImplemented;
		break;
	}

	if (ret != HPE_OK)
		PRINT_ERROR(("System error[%d], http standard error[%d]\n", ret, error_code));

	return error_code;
}


