################################################################################
################################################################################
##
## Kbuild -- Kbuild for snd-soc-gk_ipcam module
##
## (C) Copyright 2012-2017 by GOKE MICROELECTRONICS Co.,Ltd
##
################################################################################
################################################################################

EXTRA_CFLAGS        += $(PRIVATE_CFLAGS)
EXTRA_AFLAGS        += $(PRIVATE_AFLAGS)
EXTRA_LDFLAGS       += $(PRIVATE_LDFLAGS)
EXTRA_ARFLAGS       += $(PRIVATE_ARFLAGS)

    EVB_BOARD_TARGET = snd-soc-evb_audio
    obj-m += snd-soc-evb_audio.o
    $(EVB_BOARD_TARGET)-y += soc/codecs/gk_evb_audio.o

    ROOBO_BOARD_TARGET = snd-gk_pcm
    obj-m += snd-gk_pcm.o
    $(ROOBO_BOARD_TARGET)-y += soc/goke/snd-gk_pcm.o

