################################################################################
################################################################################
##
## Makefile -- makefile for ADI test application
##
## (C) Copyright 2012-2014 by Goke Microelectronics Co.,Ltd
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################


################################################################################
# source files
################################################################################

SOURCES += src/test.c

################################################################################
# define define user cc flags
################################################################################

CCFLAGS_USER += -O3 -DDEBUG -g
CCFLAGS_USER += -I $(TOPDIR)/
CCFLAGS_USER +=-I$(INSTALL_HEADER_DIR)/midware/ntpclient

################################################################################
# define define user ld flags
################################################################################

LDFLAGS_USER +=-lpthread

################################################################################
# define library used
################################################################################

LIBRARIES  += ntpclient

################################################################################
# define target name
################################################################################

PROGRAM = test_ntp

################################################################################
# define local file to be installed
################################################################################
LOCAL_FILE = 

################################################################################
# define local file install location
# if this was commented out, the target will be installed into the default
# location:
#   $(ROOTFS_TOP)/usr/local/bin/
################################################################################

INSTALL_LOCAL_FILE_DIR = 

################################################################################
# define target install location
# if this was commented out, the target will be installed into the default
# location:
#   $(ROOTFS_TOP)/usr/local/bin/
################################################################################

# INSTALL_BIN_DIR =

################################################################################
# define user targets
################################################################################

default: install

clean: clean-objects clean-all

build:  build-objects build-program

install: build install-program install-bin

headers:

all: clean build install

  RELEASE_SUBDIR = $(SUBDIR)
  RELEASE_FILES += Makefile
  RELEASE_FILES += Makefile.rel
  RELEASE_FILES += $(SOURCES)
  RELEASE_FILES += $(wildcard src/*.h)


release: release-files $(DIRECTORIES:%=subdir-release-%) info

doc: $(DIRECTORIES:%=subdir-doc-%)

info: force
	@echo $(DIRECTORIES)

