################################################################################
################################################################################
##
## Makefile.config -- project specific makefile to run build on sub directories
##
## (C) Copyright 2012-2013 by Goke Microelectronics Co.,Ltd
##
## Version: $Id: Makefile.config 3 2017-09-04 09:29:58Z fengxuequan $
##
################################################################################
################################################################################
ifndef TERM
  HOST ?= win32
  ROOT ?=
else
  ifeq ("$(TERM)","cygwin")
    HOST ?= cygwin32
    ROOT ?= /cygdrive
  else
    HOST ?= linux
    ROOT ?=
  endif
endif

ifeq ($(_GKRELEASE_), y)
include $(TOPDIR)/Config.mak.release
else
  ifeq ($(HOST),linux)
    -include $(TOPDIR)/Config.mak.$(USER)
  else
	-include $(TOPDIR)/Config.mak.$(USERNAME)
  endif
endif
include $(TOPDIR)/Config.mak
-include $(TOPDIR)/env/configs/Config.release
